### ISSUE TITLE
About vocabulary

### ISSUE THREAD

**Issue by TomasAndersonFang** [microsoft/CodeBERT#101]
Hello,

Thanks for sharing the source code of CodeBERT. When reading your paper, you said that you loaded the pre-trained Roberta model when pre-training CodeBERT. So I want to know that the vocabulary used in CodeBERT is from Roberta, or you use BBPE to train a new vocabulary whose size is equal to the vocabulary in Roberta

**Comment by guoday** [comment]
The vocabulary is directly from roberta-base.

**Comment by TomasAndersonFang** [comment]
Thanks for your answer？
