### ISSUE TITLE
unkown tokens的作用

### ISSUE THREAD

**Issue by fuqiang-git-hub** [microsoft/CodeBERT#102]
您好，我们使用了您提供的提取dataflow的方法，参照您论文以及源代码中使用的方法做了attention mask，并且使用了unknown tokens代替nodes，但是实际训练效果目前不太理想，可能是因为我们没有按照论文中的方法进行预训练，请问这个预训练是否对最终效果影响很大，引入unknown tokens的原理又是什么呢？希望您能帮助解答疑惑，谢谢

**Comment by guoday** [comment]
预训练对最终的效果影响很大。引入unknown tokens并没什么作用，因为我们输入的是tokens embedding average之后的结果，并不是unknown tokens的embedding. 如果你使用了GraphCodeBERT的预训练模型，并且在你的下游任务中效果并不理想的话，有可能dataflow对该任务用处不大。
