### ISSUE TITLE
Is it possible to release the fine-tuned weights?

### ISSUE THREAD

**Issue by leordsong** [microsoft/CodeBERT#106]
Hi there,

I have limited GPU resources, and I only want to run the evaluation process to test some datasets.
I wonder if it is possible to release the fine-tuned weights for each task? For example, "checkpoint-best-bleu" for code2nl.

Big Thanks

**Comment by guoday** [comment]
We only keep checkpoints for code2nl task. Please download the checkpoints from this [web](https://www.dropbox.com/s/sfx8ngp79cd7bwq/code2nl-model.zip) and use this [repo](https://github.com/microsoft/CodeXGLUE/tree/main/Code-Text/code-to-text) for inference.

**Comment by leordsong** [comment]
Thanks!

**Comment by clarascu** [comment]
@guoday Do you still have the checkpoint for code2nl? I'd love to use it if that's possible.

**Comment by guoday** [comment]
> @guoday Do you still have the checkpoint for code2nl? I'd love to use it if that's possible.

https://www.dropbox.com/s/az15pjc9ofj1p6h/code2nl-model.zip
