### ISSUE TITLE
Whether CodeBERT can get the calculation of semantic similarity between code and code or text and text  by the same way between text and code

### ISSUE THREAD

**Issue by lanpengyou125** [microsoft/CodeBERT#108]
Whether CodeBERT can get the calculation of semantic similarity between code and code or text and text  by the same way between text and code？Thanks
我想用CodeBERT来获取text和text之间或者code和 code之间的相似度，可以直接使用和text与code之间相同的计算方法嘛？

**Comment by guoday** [comment]
可以
