### ISSUE TITLE
GraphCodeBert在下游任务中“my-languages.so”文件报错

### ISSUE THREAD

**Issue by huangkNIPC** [microsoft/CodeBERT#109]
您好，我在运行GraphCodeBert的相关下游任务时，遇到了以下错误，希望得到您的解答。万分感谢！

  File "run.py", line 68, in <module>
    parser.set_language(LANGUAGE) 
ValueError: Incompatible Language version 11. Must be between 13 and 13

**Comment by daiquocnguyen** [comment]
Hi @huangkNIPC, I got the similar error. Would you mind telling me how to deal with this? Thanks.

**Comment by daiquocnguyen** [comment]
I solved this as I updated the latest py-tree-sitter.
