### ISSUE TITLE
Some question about the vocabulary size on CodeSearchNet corpus

### ISSUE THREAD

**Issue by Doragd** [microsoft/CodeBERT#11]
Hi, 
Thanks for your excellent work! it is really interesting.
Recently, I try to do some experiment on CodeSearchNet dataset. After preprocessing, I found the vocabulary is SO LARGE !! 
I don't know how to solve it...
I would like to know if there is a chance that let me know how you solve the so large vocabulary.
Thanks a lot.

**Comment by marscod** [comment]
@Doragd How you generate the vocabulary?

**Comment by fengzhangyin** [comment]
@Doragd We use the same vocabulary as roberta-base.

**Comment by marscod** [comment]
https://github.com/microsoft/CodeBERT/blob/master/codesearch/run_classifier.py#L501
