### ISSUE TITLE
Natural Language to code retrieval using UniXcoder

### ISSUE THREAD

**Issue by QasimKhan5x** [microsoft/CodeBERT#111]
Hi. I saw the model card of UniXcoder on huggingface. I want to use it for natural language to code retrieval. Is the pretrained model on huggingface useful for this task or should I use the CodeBERT weights that you have provided in the demo?

**Comment by guoday** [comment]
I am cleaning the code. For natural Language to code retrieval, I would like to share you with the code in advance:
[code-search.zip](https://github.com/microsoft/CodeBERT/files/8381455/code-search.zip). I will release more details about zero-shot code retrieval in next week.

**Comment by guoday** [comment]
We have uploaded UniXcoder. Please follow [this](https://github.com/microsoft/CodeBERT/tree/master/UniXcoder#2-quick-tour) for code search.
