### ISSUE TITLE
Hi  I wonder why GraphCodeBERT can take sequence as long as 640(512 for code tokens plus 128 for data flow)?

### ISSUE THREAD

**Issue by Anothernewcomer** [microsoft/CodeBERT#113]
Thanks in advance for your reply!

**Comment by guoday** [comment]
Because data flow don't need to use position embeddings.

**Comment by Anothernewcomer** [comment]
> Maximum sequence length of pre-trained models depend on position embeddings size (514 in GraphCodeBERT). However, data flow doesn't need to use position embeddings. Therefore, you can use as long data flow as possible.

Thanks very much , you really help me a lot  ><
