### ISSUE TITLE
预训练模型的源码

### ISSUE THREAD

**Issue by MrBlack0220** [microsoft/CodeBERT#115]
您好，请问预训练模型的源码可以从哪里查看呢？非常感谢

**Comment by MrBlack0220** [comment]
codebert预训练encoder = model_class.from_pretrained(args.model_name_or_path,config=config)，如何查看encoder部分源码呢？即microsoft/codebert-base。非常感谢

**Comment by guoday** [comment]
https://github.com/huggingface/transformers/blob/main/src/transformers/models/roberta/modeling_roberta.py

**Comment by MrBlack0220** [comment]
您好，我是一名刚刚入门深度学习的萌新，目前正在学习codebert的源码，我想请教下：run.py中，encoder = model_class.from_pretrained(args.model_name_or_path, config=config）是在加载预训练模型的参数嘛？如果是的话，这里是直接用codebert预训练好的参数初始化  还是用roberta原始的参数初始化呢？另外，论文中提到的Replaced Token Detection (RTD)部分的源码从哪里查看呢？感谢您的帮助

**Comment by guoday** [comment]
`encoder = model_class.from_pretrained(args.model_name_or_path, config=config` 这个是创建预训练模型，并且加载参数。加载什么参数取决于args.model_name_or_path。如果是roberta-base就加载roberta原始的参数，如果是microsoft/codebert-base就加载codebert的参数。

论文中提到的Replaced Token Detection (RTD)是预训练的部分，我们还没公开预训练代码。我只提供预训练好的模型进行下游实验
