### ISSUE TITLE
Pre-processing data for zero-shot code-to-code search

### ISSUE THREAD

**Issue by Aviator16** [microsoft/CodeBERT#118]
Hello, I am trying to use Zero-shot Code-to-Code Search and the readme file mentions a preprocess.py file to use on our data before feeding it to the program, but there is no preprocess.py file provided in the zero-shot-search directory.
I tried feeding data in text format, but the run.py file uses json files as input. Can you please help? 
If the candidate and query files need to be provided in json, what should be the schema for these files, which basically contain functions or lines of code in a programming language.

**Comment by guoday** [comment]
please reclone the repo. I have uploaded the preprocess.py file

**Comment by Aviator16** [comment]
Thank you for your response! I was able to use the model.
