### ISSUE TITLE
code search 模型预测

### ISSUE THREAD

**Issue by PL2584718785** [microsoft/CodeBERT#119]
您好，大佬   看完您的工作，我收获颇多、受益匪浅   目前遇到一个问题想向您请教下，如论文中图4中所示的 Case Study，我应该如何做才能实现输入一个query，输出一个相应的函数代码快呢(output predictions)？   非常感谢！

**Comment by guoday** [comment]
这两个都可以参考
https://github.com/microsoft/CodeBERT/tree/master/GraphCodeBERT/codesearch#model-and-demo
https://github.com/microsoft/CodeBERT/tree/master/UniXcoder#2-similarity-between-code-and-nl

**Comment by PL2584718785** [comment]
> 这两个都可以参考 https://github.com/microsoft/CodeBERT/tree/master/GraphCodeBERT/codesearch#model-and-demo https://github.com/microsoft/CodeBERT/tree/master/UniXcoder#2-similarity-between-code-and-nl

好的 大佬，非常感谢  参考了这两个测试用例，
自己写了下，然后运行以下代码：
query = "set a variable as hello world"
tokens_ids = model.tokenize([query],max_length=512,mode="<encoder-only>")
source_ids = torch.tensor(tokens_ids).to(device)

prediction_ids = model.generate(source_ids, decoder_only=False, beam_size=3, max_length=128)
predictions = model.decode(prediction_ids)

print(predictions)


输出结果如下：
'''
def set_hello_world(self, name, value):
        if name in self.variables:
            self.variables[name] = value

def set_hello_world(self, name, value):
        if name in self.variables:
            self.variables[name].value = value

def set_hello_world(self, name, value):
        if name not in self.variables:
            self.variables[name] = value
'''
**得到的代码块 ，感觉跟大佬您给出的示例差得很远，不知道该如何优化code search预测脚本，麻烦大佬指导下，谢谢**
[这是大佬您给出跟query相对应的代码片段
code_1="print('hello world')"
code_2="s = 'hello world'"
code_3="hello world"]

**Comment by guoday** [comment]
你不是做code search，为什么要用generate? code search是你要对code和nl做编码，然后算余弦值。所以你首先要有个代码库，然后将代码全部编码成向量。再用query的向量做检索
