### ISSUE TITLE
Training and validation datasets

### ISSUE THREAD

**Issue by marscod** [microsoft/CodeBERT#12]
Do you plan to publish generator code of training and validation datasets? 
It seems that you have created 1 positive record for even records in CodeSerachNet; 2 negative and 1 positive for odds records in CodeSearchNet. Am I right?

**Comment by fengzhangyin** [comment]
Hi @marscod ,
Data processing is very simple. We keep all instances from CodeSearchNet as positive examples, and randomly replace NL or PL in each instance to generate negative examples. In the end, positive and negative samples are balanced, and negative samples consist of balanced number of instances with randomly replaced NL(pl, nl<sup>random</sup>) and PL(pl<sup>random</sup>, nl).

**Comment by marscod** [comment]
Thanks for the prompt response.
