### ISSUE TITLE
UniXcoder实例

### ISSUE THREAD

**Issue by sunhao123456789** [microsoft/CodeBERT#121]
师兄，对于CodeBERT/UniXcoder/中的codedetection工作，能给一个使用实例吗？想获得输入的code的embedding.

**Comment by sunhao123456789** [comment]
还有师兄，对于graphcodebert/和UniXcoder/中的codedetection工作，输入一个code，code有一共有5行代码，25个token，想获得这个code中的每行代码的embedding，这样能分别给个运行实例吗？谢谢师兄

**Comment by guoday** [comment]
请参考unixcoder的readme，clone detection的样例，和每个token的embedding都有给出
