### ISSUE TITLE
graphcodebert使用

### ISSUE THREAD

**Issue by sunhao123456789** [microsoft/CodeBERT#122]
师兄你好，请问：
（1）当对C/C++代码做code clone detection的时候，直接使用codebert/graphcodebert，Precision大约能达到多少呢？
（2）对于单模态的codebert/graphcodebert,比如只有comment/code,怎么使用codebert/graphcodebert?能贴下代码吗？
谢谢。

**Comment by guoday** [comment]
1）不清楚，不同数据集有不同的结果。直接使用一般不会高，可参考unixcoder的zero-shot code-code search的结果
2）https://github.com/microsoft/CodeBERT#nl-pl-embeddings。将这里的comment+[sep]或者code+[sep]部分删掉即可
