### ISSUE TITLE
NL, PL probing task

### ISSUE THREAD

**Issue by brutalsavage** [microsoft/CodeBERT#123]
Regarding NL and PL probing task used to evaluate CodeBERT, there are a few unclear issues that I hope you can clarify

- **Number of datapoints for probing:** In the CodeBERT paper, it is described that only test and valid data from codesearchnet is used to evaluate probing. Take PL probing for example where only codes containing _max_ or _min_ is chosen, however I can't get the same number of datapoints reported in Table 3 (for example: python-paper: 1264, me: 1246, java-paper: 482, me: 556). I grab the dataset following the codesearchnet repo and only exclude data that tokenize to longer than 512 tokens. Do you guys do additional processing to adjust the dataset size for probing?
- **Probing NL tokens:** In this task, the paper describes 6 keywords that are used _max_, _maximizer_, _min_, _minimize_, _less_, and _greater_ and group into 4 categorizes. However using the tokenizer, different keywords can tokenize to different length of tokens. For example _greater_ tokenizes to 2 different tokens (_great_ and _er_). In this case does the NL probing evaluation only tokenizer the first token (i.e <mask> _er_) ? If so, is it really a fair evaluation? since its unlikely the model will ever predict _maxer_ since its not a word in the english language.

**Comment by fengzhangyin** [comment]
- We don't do additional processing. We have released the max/min ClozeTest in [CodeXGLUE](https://github.com/microsoft/CodeXGLUE). You can find this dataset in this [repo](https://github.com/microsoft/CodeXGLUE/tree/main/Code-Code/ClozeTesting-maxmin).
- We replace the _max, maximizer, min, minimize, less and greater_ with _[MASK]_ before tokenization. So there will be no such situation as you said. We specify that the masked position corresponds to one of _max, min, less, and great_.
