### ISSUE TITLE
我可以通过微调GraphCodeBERT来训练一个代码搜索基线模型吗?

### ISSUE THREAD

**Issue by Dengzhongyang399** [microsoft/CodeBERT#127]
大佬您好，我想请教一个问题.
我根据https://github.com/microsoft/CodeBERT/tree/master/GraphCodeBERT/codesearch#model-and-demo 中给出的训练脚本，将预训练模型设置为microsoft/graphcodebert-base，然后在我的数据集上训练出来的模型能视为基于GraphCodeBERT的代码搜索模型吗？我想将其视为对比的基线模型。

**Comment by guoday** [comment]
可以

**Comment by Dengzhongyang399** [comment]
> 可以

好的，非常感谢！
