### ISSUE TITLE
(minor) output_dir path of CSN fine-tuning commands in CodeBERT/UniXcoder/downstream-tasks/code-search/README.md

### ISSUE THREAD

**Issue by stovecat** [microsoft/CodeBERT#128]
It would be better to modify output_dir path of CSN fine-tuning commands:
from
`--output_dir saved_models/cosqa \`
to
`--output_dir saved_models/CSN/$lang \`

**Comment by guoday** [comment]
Thanks, update done.

**Comment by stovecat** [comment]
Thanks :)
