### ISSUE TITLE
Where could I find the code for comparison in CodeSearch task?

### ISSUE THREAD

**Issue by iamfaith** [microsoft/CodeBERT#130]
Thanks for your great work! Could you please provide the code for the comparison mentioned in the paper? I would like to reproduce your work? Could you please send me the code to my email (xianzixiang@gmail.com) if possible?

Many thanks in advance.

**Comment by guoday** [comment]
We have released the code in the repo. Please find CodeBERT/GraphCodeBERT/UniXcoder code search folder.

**Comment by iamfaith** [comment]
sorry, I cannot see any folder of unixcode in the graghcodebert
 folder. Which branch, please?

**Comment by guoday** [comment]
https://github.com/microsoft/CodeBERT/tree/master/UniXcoder

**Comment by iamfaith** [comment]
You may misunderstand what I said. I am curious about whether the compared models, as shown in highlighted image mentioned in the original codebert paper, are available in this repo or not.
![image](https://user-images.githubusercontent.com/16201784/166403527-496f3910-5798-47ad-9553-84e55f01248e.jpeg)

**Comment by guoday** [comment]
The baseline comes from CodeSearchNet: https://arxiv.org/pdf/1909.09436.pdf. You can find compared models in their repo.

**Comment by iamfaith** [comment]
Great thanks！ You help me a lot. I will close this issue.
