### ISSUE TITLE
Replace 'pip sklearn' with 'pip install scikit-learn' in GraphCodeBert dependency

### ISSUE THREAD

**Issue by skaghzz** [microsoft/CodeBERT#136]
[GraphCodeBert dependency](https://github.com/microsoft/CodeBERT/tree/master/GraphCodeBERT/clonedetection#dependency)
On pip, 'sklearn' is different with 'scikit-learn'
it should be change to 'pip install scikit-learn'

Note
[sklearn](https://pypi.org/project/sklearn/)
[scikit-learn](https://pypi.org/project/scikit-learn/)

**Comment by guoday** [comment]
thanks.
