### ISSUE TITLE
Code Clone Detection任务指标复现问题

### ISSUE THREAD

**Issue by mrhu2017** [microsoft/CodeBERT#137]
您好，在 GraphCodeBERT 论文 v1 里， Code Clone Detection任务的结果是

                                         precision                           Recall                               F1
CodeBERT                              96.4                                96.6                               96.5
GraphCodeBERT                    97.3                                96.8                               97.1

很多工作也引用了这个结果，但在v4版本的论文里，结果更新成了：

                                         precision                           Recall                               F1
CodeBERT                             94.7                               93.4                               94.1
GraphCodeBERT                   94.8                                95.2                               95.0

这个和开源代码的结果是一致的，请问造成这两版实验结果的差异的原因是什么？应该以哪一版的结果为准？如果想复现97.1的结果，应该怎么做，谢谢~

**Comment by guoday** [comment]
邮件已回复

**Comment by mrhu2017** [comment]
您好，我已收到您的邮件，会尽快回复~
