### ISSUE TITLE
Code search demo code?

### ISSUE THREAD

**Issue by lalenzos** [microsoft/CodeBERT#138]
Hi,
is there a demo code or example project that shows how to apply code search?
More specifically, I am interested in how to search in multiple code files so that you get a single line or code block as a search result.

Thanks.

**Comment by guoday** [comment]
You can follow this [command](https://github.com/microsoft/CodeBERT/tree/master/UniXcoder#3-encoder-only-mode) to encode code into vectors and then search using cosine distance.
