### ISSUE TITLE
zero-shot-search dataset

### ISSUE THREAD

**Issue by wangdeze18** [microsoft/CodeBERT#140]
When I run the zero-shot-search task of unixcoder, I get an error with running process.py.

![image](https://user-images.githubusercontent.com/55313414/171550040-206cba64-8d22-4eee-aca4-f7d128e0b940.png)

The reason seems to be that the file displayed on the right side of the figure is inconsistent with the downloaded CodeNet corpus.

Thanks.

**Comment by guoday** [comment]
I don't know what your problem is.  Please follow this [readme](https://github.com/microsoft/CodeBERT/tree/master/UniXcoder/downstream-tasks/zero-shot-search#data-download) to download CodeNet and extract function.

**Comment by wangdeze18** [comment]
Yes, I followed this readme and got this error. Specifically, the labels of the downloaded dataset (e.g., p00027) are inconsistent with that of the jsonl file (e.g., 3533). None of the folders in the downloaded dataset is p03533.

**Comment by guoday** [comment]
`>ls Project_CodeNet/data/p03533/`
`Awk  C  C#  C++  D  Go  Haskell  Java  JavaScript  Julia  Kotlin  Lisp  Lua  OCaml  PHP  Pascal  Perl  Python  Ruby  Rust  Scala  Sed`

I have checked the folder and the p03533 folder exists. Maybe you can use `ls Project_CodeNet/data/p03533/` command to check.

**Comment by wangdeze18** [comment]
I'm sorry to bother you and my local file is incomplete.
