### ISSUE TITLE
valid/test dataset format for clone detection of GraphCodeBERT

### ISSUE THREAD

**Issue by saekomdalkom** [microsoft/CodeBERT#141]
Hello, I'm trying to use your GraphCodeBERT code for clone detection and I have a question. (Sorry in advance that I'm newbie of this field.)

In sample dataset train/valid/test.txt file they only have idx instead of code itself and it seems the actual codes are at data.jsonl. I understand they only have idx for train dataset but it's hard to understand validation and test dataset only have idx too. Does it mean data.jsonl has all the codes including codes for validation and test dataset? Then when the new codes come should I add them into data.jsonl again?

**Comment by guoday** [comment]
Yes.

**Comment by saekomdalkom** [comment]
Oh I see. Thank you for your quick answer!
