### ISSUE TITLE
ValueError: num_samples should be a positive integer value, but got num_samples=0

### ISSUE THREAD

**Issue by saekomdalkom** [microsoft/CodeBERT#142]
Hello, I'm trying to use your code for clone detection, 
so I made dataset/train.txt as [idx1 idx2 label] format but this error is occuring.

06/06/2022 11:43:25 - INFO - __main__ -   Creating features from index file at dataset/train.txt 
0it [00:00, ?it/s]
Traceback (most recent call last):
  File "run.py", line 624, in <module>
    main()
  File "run.py", line 602, in main
    train(args, train_dataset, model, tokenizer)
  File "run.py", line 325, in train
    train_sampler = RandomSampler(train_dataset)
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/sampler.py", line 98, in __init__
    "value, but got num_samples={}".format(self.num_samples))
ValueError: num_samples should be a positive integer value, but got num_samples=0

Current dataset/train.txt is like this. 

691	1178	1
14120	15265	1
23800	24910	0
20034	21141	1
1420	1500	1
35565	36364	0

and dataset/data.jsonl is like this. 

{"func":"for i in range(1,10):\n  for j in range(1,10):\n\tprint \"%dx%d=%d\" % (i,j,i*j)","idx":0}
{"func":"for i in range(9):\n\tfor k in range(9):\n\t\tprint str(i+1) + 'x' + str(k+1) + '=' + str((i+1) * (k+1))","idx":1}
{"func":"def mul(num1,num2):\n\tprint(f\"{num1}x{num2}={num1*num2}\")\nfor i in range(1,10):\n\tfor j in range(1,10):\n\t\tmul(i,j)","idx":2}
{"func":"l = [i for i in range(1,10)]\nfor i in l:\n  for j in l:\n\tprint(str(i)+ 'x' + str(j) + '=' + str(i*j))","idx":3}

Can you tell me what I did wrong?

**Comment by guoday** [comment]
You can try to debug why the `len(data) == 0` here:
https://github.com/microsoft/CodeBERT/blob/567dd49a4b916835f93fb95709de714b8772fea2/UniXcoder/downstream-tasks/clone-detection/BCB/run.py#L120-L133
