### ISSUE TITLE
UniXcoder fine-tune code summarizaion问题

### ISSUE THREAD

**Issue by edisonh** [microsoft/CodeBERT#146]
你好，
按照readme参数fine-tune，两代之后就达到了best blue，再过两代就触发了两代blue无进展就退出的逻辑。
请问要调整哪些参数、大致要怎么调才能进一步提升blue？
先谢了。

**Comment by guoday** [comment]
你好，我并没有仔细调code summarizaion，确实收敛比较快。参数的话，可以就是学习率和batch size，但应该提升都不大

**Comment by edisonh** [comment]
@guoday  感谢
