### ISSUE TITLE
results of code search task

### ISSUE THREAD

**Issue by wangdeze18** [microsoft/CodeBERT#148]
Hello, I noticed that Table 5 in the unixcoder paper contains the code search results of codet5， but the original codet5 has no results on code search. How can I reproduce this result? （Loading the pretrained model directly or something else？）

**Comment by guoday** [comment]
Replace UniXcoder by CodeT5 and use the mean pooling of hidden states of decoder for code search.

**Comment by wangdeze18** [comment]
Thanks!
