### ISSUE TITLE
OOV word embedding & Train GraphCodeBERT on downstream tasks

### ISSUE THREAD

**Issue by ziwenyd** [microsoft/CodeBERT#149]
Thanks for the great work done! I have some questions regarding the vocabulary.

1. how does GraphCodeBERT generate word embedding for out-of-vocabulary words (if it does not generate, how can I know that it is an OOV word)?
2. Can I see the vocabulary list & how?
3. If there is an OOV problem, can I further train the 'microsoft/graphcodebert-base' on my corpus & how?

4. I got the suggestion message below when loading the 'microsoft/graphcodebert-base' as encoder. Looks like the released pre-trained model is the general GraphCodeBERT model and to get a good performance we should train the 'microsoft/graphcodebert-base' on the downstream task( e.g. code-translation): 

    Does the paper's work of code translation also trained the model on top of 'microsoft/graphcodebert-base' ? (from the [run.py ](https://github.com/guoday/CodeBERT/blob/master/GraphCodeBERT/translation/run.py)looks like it only tries to optimize the hyper parameter instead of re-training the word embeddings)

```
from transformers import (WEIGHTS_NAME, AdamW, get_linear_schedule_with_warmup,
                          RobertaConfig, RobertaModel, RobertaTokenizer)
model_type = 'roberta'
config_class = RobertaConfig
model_class = RobertaModel
tokenizer_class = RobertaTokenizer
config_name='microsoft/graphcodebert-base'
pretrained_model='microsoft/graphcodebert-base'
tokenizer_name='microsoft/graphcodebert-base'

config = config_class.from_pretrained(config_name)
tokenizer = tokenizer_class.from_pretrained(tokenizer_name)
encoder=model_class.from_pretrained(pretrained_model, config=config)
```

```
Some weights of the model checkpoint at microsoft/graphcodebert-base were not used when initializing RobertaModel: ['lm_head.bias', 'lm_head.layer_norm.weight', 'lm_head.dense.bias', 'lm_head.decoder.bias', 'lm_head.decoder.weight', 'lm_head.dense.weight', 'lm_head.layer_norm.bias']
- This IS expected if you are initializing RobertaModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing RobertaModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of RobertaModel were not initialized from the model checkpoint at microsoft/graphcodebert-base and are newly initialized: ['roberta.pooler.dense.weight', 'roberta.pooler.dense.bias']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
transformers.models.roberta.modeling_roberta.RobertaModel
```

Many thanks!

**Comment by guoday** [comment]
1. We use a BPE vocabulary and it can split any words into a sequence of vocabulary words. Therefore, you don't need to care about OOV.
2. https://huggingface.co/microsoft/unixcoder-base/tree/main
3. As said in 1), there is not OOV problem for BPE vocabulary.
4. We reload the parameters of GraphCodeBERT model (including word embeddings and Transformer) and fine-tune on downstream tasks.
