### ISSUE TITLE
Fine-tuned models

### ISSUE THREAD

**Issue by poojitharamachandra** [microsoft/CodeBERT#153]
Are the fine-tuned models available for use?
I am looking for fine-tuned model on 'C' PL for code summarization

**Comment by poojitharamachandra** [comment]
Can I use the model @https://huggingface.co/microsoft/unixcoder-base-nine/tree/main and the example @ https://github.com/microsoft/CodeBERT/tree/master/UniXcoder#3-code-summarization to generate summaries without fine-tuning?

is it necessary to have the code in the format : context = """
# <mask0>
def write_json(data,file_path): ?


especially #<mask0>?

**Comment by guoday** [comment]
Yes. You can. 

You need to have a special token `<mask0>` to tell the model where need to fill the content. Thus, you need to choose the position according to the language.

**Comment by guoday** [comment]
For example, if you use C language, you may use // `<mask0>`. Since the model is a pre-trained model without fine-tune, you must follow the real format.

**Comment by poojitharamachandra** [comment]
Thanks!

Can I provide a .c or .json file (containing source code) as the input while testing?

**Comment by guoday** [comment]
In fact, you can modify the code by yourself, so that it can support files as the input.

**Comment by poojitharamachandra** [comment]
Hi, could you provide a sample for input file for codesearch task?

**Comment by guoday** [comment]
No. You can load the file and write a loop statement to generation summarization for each code.

**Comment by guoday** [comment]
https://github.com/microsoft/CodeBERT/tree/master/UniXcoder#3-encoder-only-mode

**Comment by poojitharamachandra** [comment]
How do I give a batch of examples through a file? In what format should the file contain the data?

**Comment by guoday** [comment]
We only provide an example to tell how to use the model to calculate the similarity of a code and a text (https://github.com/microsoft/CodeBERT/tree/master/UniXcoder#3-encoder-only-mode).  You need to implement the remaining part by yourself, including collecting code corpus, encoding them into embeddings, retrieving code by cosine distance.

**Comment by poojitharamachandra** [comment]
thanks.
But there is option for fine tuning and evaluating mentioned in https://github.com/microsoft/CodeBERT/tree/master/UniXcoder/downstream-tasks/code-search#fine-tune-setting
Could you let me know what format the .jsonl files are ( eg: --train_data_file dataset/AdvTest/train.jsonl )

**Comment by guoday** [comment]
https://github.com/microsoft/CodeXGLUE/tree/main/Text-Code/NL-code-search-Adv#data-format
