### ISSUE TITLE
能帮我看个问题吗？我用codebert跑codesearch任务，在go语言上MRR分数最多到0.84，很难达到0.88+。

### ISSUE THREAD

**Issue by fanzhang2021** [microsoft/CodeBERT#157]
代码和配置文件是直接git pull下来的，没有进行修改，具体配置就是这个页面：https://github.com/microsoft/CodeBERT/tree/master/CodeBERT/codesearch

我用的pytorch1.12，2080TI，P100。

也尝试过将batch_size放大，但是还是上不去。

**Comment by guoday** [comment]
在CodeBERT论文中，MRR分数就是0.8400

**Comment by guoday** [comment]
GraphCodeBERT的论文已经说过如何过滤一些数据了，所以两者数据不同
