### ISSUE TITLE
How to deal with long code data?

### ISSUE THREAD

**Issue by LIUZHENGYU2019** [microsoft/CodeBERT#16]
I am using codeBERT for classifying malicious code written in PHP. Some codes in the dataset are really long which far beyond the general MAX_LEN of a sentence for example 256. And setting MAX_LEN a big number would soon result in GPU resources exhausted. So I wonder if there are some fine strategies to deal with it.

**Comment by guoday** [comment]
Our model only supports 512 max length. One strategy is that you can split a code into `K` segments, and then feed `K` segments into CodeBERT separately. Finally, you average or use a RNN over `K` representations of CodeBERT to obtain a global representation.

**Comment by LIUZHENGYU2019** [comment]
Thankyou! It did solve my problem!

**Comment by Silverhorse7** [comment]
I am using CodeBERT embeddings in my module, does the result embeddings get affected by the token size too? @guoday
