### ISSUE TITLE
CodeReviewer infer got error

### ISSUE THREAD

**Issue by BrightHai** [microsoft/CodeBERT#160]
![image](https://user-images.githubusercontent.com/11002329/182995992-76dd062f-6f7b-46cd-bca1-9dded629af6d.png)
![image](https://user-images.githubusercontent.com/11002329/182996074-f9f8d36c-fb16-42a0-8dd4-5c673de7e574.png)

**Comment by celbree** [comment]
Hi, it seems I cannot reproduce this error. But I still pushed a new commit to fix this error https://github.com/microsoft/CodeBERT/commit/4af7b00268755a2df7eb5491621296cb3ea1f557. Please try using the newest code.

**Comment by BrightHai** [comment]
@celbree  Thanks for your reply，it would be better if you provide testing samples  in readme
