### ISSUE TITLE
麻烦帮看一下GraphCodeBERT中，train、valid数据集的label问题。

### ISSUE THREAD

**Issue by fanzhang2021** [microsoft/CodeBERT#161]
现在，我通过https://github.com/microsoft/CodeBERT/tree/master/GraphCodeBERT/codesearch#data-preprocess的指导，能够得到**过滤后**的train、valid和test数据集。但是这些数据集没有label。

如果我想用codebert在**过滤后的**train数据集上fine turn时，就需要lable数据。

我在graphcodebert论文中的Appendix B，看到了Code Search在过滤后的数据集上测试结果。但是我没有找到如何将过滤后的数据，进一步制造出带lable的数据。

所以：我想知道的是：有没有脚本或者别的信息，可以在过滤后的数据集上，制造出带lable的数据呢，就像codebert之前用的数据那种，train，valid数据集都是有lable的。

**Comment by guoday** [comment]
每条数据都有一个NL和Code，他们就是正样本，其他的NL-code pair就是负样本

**Comment by guoday** [comment]
没，随机采样即可
