### ISSUE TITLE
UniXCoder in API Recommendation - Extracting API Sequences

### ISSUE THREAD

**Issue by happygirlzt** [microsoft/CodeBERT#163]
Hi there, thank you for open sourcing!
I have a question regarding the data used for API recommendation task. https://github.com/microsoft/CodeBERT/tree/master/UniXcoder#2-api-recommendation
It looks like we need first to extract the API sequences and then mask them.
I was wondering which script was used to extract API sequences. Or do you use regex to parse the API sequences? Or is there any ready dataset that can be used for evaluating the API recommendation task with UniXcoder?
Thank you very much in advance!

**Comment by guoday** [comment]
No, we don't use any tool to mask the API sequences. It's just a demo to show the ability of UniXcoder. If you need to automatically mask API sequences, I suggest you use [tree-sitter](https://github.com/tree-sitter/py-tree-sitter) to parse a code to a AST and then find APIs to mask.

We don't have any dataset that cab be used for evaluating the API recommendation task.

**Comment by happygirlzt** [comment]
OK, thank you very much for the information and suggestion!
