### ISSUE TITLE
can I get embedding for java code snippet?

### ISSUE THREAD

**Issue by ramsey-coding** [microsoft/CodeBERT#164]
I am looking into the following example to extract code embedding.

```
# Encode maximum function
func = "def f(a,b): if a>b: return a else return b"
tokens_ids = model.tokenize([func],max_length=512,mode="<encoder-only>")
source_ids = torch.tensor(tokens_ids).to(device)
tokens_embeddings,max_func_embedding = model(source_ids)
```

So I suppose I can get embedding for a python function from this `max_func_embedding`.

However, I have the following three questions:

a) Can I use CodeBERT to extract embedding for Java code?

b) Can I feed incomplete JavaScript code to extract embedding? Or the code snippet needs to be complete?

And most importantly:
c) Can I feed multiple function and get embedding for the whole snippet?

Lets say the code snippet has two functions and slightly incomplete:

```
testCreateProcessDefinitionQuery ( ) { 
org . foxbpm . engine . repository . ProcessDefinitionQuery processQuery = modelService . createProcessDefinitionQuery ( ) ; "<AssertPlaceHolder>" ; 
} 

createProcessDefinitionQuery ( ) { 
return new org . foxbpm . engine . impl . model . ProcessDefinitionQueryImpl ( commandExecutor ) ; 
}
```
Will Unixcoder even generate embedding for this case?

**Comment by ramsey-coding** [comment]
@guoday please help 🙏

**Comment by guoday** [comment]
a) You can. Please follow CodeBERT readme. But the embeddings are not good.
b) You can feed incomplete JavaScript code
c) You can try. But I am not sure the performance of the embeddings, since we only use single function as pre-training data.

**Comment by ramsey-coding** [comment]
@guoday What would be your response if I try this with `UniXcoder`? Really looking forward to your response.

**Comment by guoday** [comment]
You can try to use UniXcoder.

**Comment by ramsey-coding** [comment]
@guoday is the UniXcoder a better bit for feeding multiple function and get embedding for the whole snippet? Example below:

```
testCreateProcessDefinitionQuery ( ) { 
org . foxbpm . engine . repository . ProcessDefinitionQuery processQuery = modelService . createProcessDefinitionQuery ( ) ; "<AssertPlaceHolder>" ; 
} 

createProcessDefinitionQuery ( ) { 
return new org . foxbpm . engine . impl . model . ProcessDefinitionQueryImpl ( commandExecutor ) ; 
}
```

**Comment by guoday** [comment]
yes
