### ISSUE TITLE
Taking too much memory in GPU

### ISSUE THREAD

**Issue by abhishek-ch** [microsoft/CodeBERT#166]
I am trying to run an example with 1000+ datasets to train where max characters are 260 and when I am trying to train that in GPU, it's taking more than 15GB+ memory.
Why is `model(source_ids)` taking too much memory?

```
tokens_ids = model.tokenize([func],max_length=260,mode="<encoder-only>")
source_ids = torch.tensor(tokens_ids).to(device)
tokens_embeddings,max_func_embedding = model(source_ids)
```

Is there any spec to understand how much memory this model takes for generating embeddings?

**Comment by guoday** [comment]
Try to use the following script to extract features [extract_features.zip](https://github.com/microsoft/CodeBERT/files/9446140/extract_features.zip). I have used it in [AI4Code competition](https://www.kaggle.com/competitions/AI4Code/leaderboard) and have no problems in my server.

**Comment by guoday** [comment]
Hi @abhishek-ch. Do you try the script? I want to know whether it works for you?

**Comment by abhishek-ch** [comment]
It didn't help, I needed to add Significant large GPU memory to run it. CPU was not possible.

**Comment by guoday** [comment]
You can try to use smaller batch size.


------------------ Original ------------------
From: Abhishek Choudhary ***@***.***&gt;
Date: Sat,Sep 17,2022 5:01 AM
To: microsoft/CodeBERT ***@***.***&gt;
Cc: Daya Guo ***@***.***&gt;, Comment ***@***.***&gt;
Subject: Re: [microsoft/CodeBERT] Taking too much memory in GPU (Issue #166)





 
It didn't help, I needed to add Significant large GPU memory to run it. CPU was not possible.
