### ISSUE TITLE
Doubt related to input format for CodeBERT

### ISSUE THREAD

**Issue by Tamal-Mondal** [microsoft/CodeBERT#167]
Hi Team,

Thanks for the excellent work, first of all!

I want to give multiple codes and natural language sequences as input in an interleaved way for a single datapoint to CodeBERT. 

Expected Input Format: [CLS]code_tokens_1[SEP]nl_tokens_1[SEP]code_tokens_2[SEP]nl_tokens2.....

As given in examples, we can use "<\/s>" as a separator, but examples have only a pair of code and natural language tokens. So, is it okay to extend the approach for multiple segments, or is there some limitation for codeBERT?

Thanks & Regards,
Tamal Mondal

**Comment by guoday** [comment]
It's okay to extend the approach for multiple segments, using <s>code_tokens_1</s>nl_tokens_1</s>code_tokens_2</s>nl_tokens2</s>
