### ISSUE TITLE
unable to load huge data

### ISSUE THREAD

**Issue by poojitharamachandra** [microsoft/CodeBERT#172]
hi,
 I am trying to perform coder using unixcoder and fine tuning the model with ~25k- training set. But the code is stuck at 
https://github.com/microsoft/CodeBERT/blob/4af7b00268755a2df7eb5491621296cb3ea1f557/UniXcoder/downstream-tasks/code-search/run.py#L229

do u have any suggestion for this problem?

**Comment by guoday** [comment]
It seems the cpu memory is limited. You can try to split data into several set for code searching.
