### ISSUE TITLE
Questions about UniXcoder

### ISSUE THREAD

**Issue by Youngmi-Park** [microsoft/CodeBERT#173]
Hi, I have some questions about UniXcoder.
1)  Did you alternately use each objective to pre-train the model both in unimodal and mutimodal data?
> At each iteration, we alternate each objective to pre-train the model and follow Guoetal.(2020)

2) What do source input and target input mean in encoder-decoder mode?
> For encoder-decoder mode, tokens in the source input are allowed to attend to each other, while tokens in the target input only attend to itself and previous tokens in both source and target inputs.

3) Isn't Flatten AST used in fine tuning?

**Comment by guoday** [comment]
> Hi, I have some questions about UniXcoder.
> 
> 1. Did you alternately use each objective to pre-train the model both in unimodal and mutimodal data?
> 
> > At each iteration, we alternate each objective to pre-train the model and follow Guoetal.(2020)
> 
> 2. What do source input and target input mean in encoder-decoder mode?
> 
> > For encoder-decoder mode, tokens in the source input are allowed to attend to each other, while tokens in the target input only attend to itself and previous tokens in both source and target inputs.
> 
> 3. Isn't Flatten AST used in fine tuning?

1. Yes. But for unimodal data, we remove those objectives that need NL.
2. Source/Target input means input/output. Taking code generation as an example, NL is source input and code is target input.
3. No. We only use AST in pre-training.

**Comment by Youngmi-Park** [comment]
Thanks for your reply! 
In addition to this, I have a few questions.

1. Do you have any plans to release pre-training code?

2. How can i make `Flattened AST`?

3. How did you concatenate `prefix`, `comment` and `Flattened AST`?

**Comment by guoday** [comment]
1. We don't have plans to release pre-training code currently.
2. https://github.com/microsoft/CodeBERT/issues/134#issuecomment-1127643876
3. https://github.com/microsoft/CodeBERT/blob/0b522a6d7b2e25456e52b1c99a8e9cc6cd2aa6e0/UniXcoder/unixcoder.py#L47-L58

**Comment by Youngmi-Park** [comment]
thank you!
But question 3. I think that code is used in downstream task. 
I would like to know how to concatenate prefix, comment and FlattenedAST in pre-training.

**Comment by guoday** [comment]
Concat comment and code into a string, and then parsing the string into a flattened AST. The input is [CLS][Mode][SEP] Flattened AST [SEP].
