### ISSUE TITLE
Question about using CodeBERT and other models for code search and code summarization

### ISSUE THREAD

**Issue by pdhung3012** [microsoft/CodeBERT#174]
Hello.
I have a dataset of pairs of comment - codes for our project in Chemistry. I want to implement the code search and code summarization approaches based on the query-candidate search system as follows:
For code search, given the query q1 (for code comment) and list of candidates [c1, c2,c3] as the source code snippets :
1. Get the embedding of q1 (by four models used in the repository: CodeBERT, GraphCodeBERT, UnixEncoder cand CodeReviewer),
2. Get the embeddings of c1, c2, and c3.
3. Calculating the euclidean distance between q1-c1, q1-c2, and q1-c3 to find the lowest euclidean distance to q1 as the result of the code search.

For code summarization, change query q1 to code snippets and a list of candidates as comments.
To speed up the code search and code summary, we can use the dimension reduction for the embedding like t-sne (currently the output of CodeBERT and GraphCodeBERT have 768 dimensions which took longer time for calculation).

Do you think it's reasonable to implement the system like that?
Thank you

**Comment by guoday** [comment]
For code search, it's reasonable. But for code summarization, it's better to use generation model to generate summary.

**Comment by pdhung3012** [comment]
Thanks
