### ISSUE TITLE
Question about reproducing results of UniXcoder on POJ-104

### ISSUE THREAD

**Issue by XZ-X** [microsoft/CodeBERT#175]
Dear developers,

Thank you for your efforts to consistently deliver high-quality models to the community.

Recently, I am trying to reproduce the results of UniXocde on the dataset POJ-104. I followed the training script in `UniXcoder/downstream-tasks/clone-detection/POJ-104/README.md` and got an MAP of 86.78. The number has a very slight difference with the reported results in the UniXcoder paper, which is ~90. I just want to confirm whether my setup is correct? And would you kindly share some ideas about what might be the factors introducing the variance? 

My running script:
```
export CUDA_VISIBLE_DEVICES=1,2,3,4
python run.py \
    --output_dir saved_models\
    --model_name_or_path microsoft/unixcoder-base \
    --do_train \
    --train_data_file dataset/train.jsonl \
    --eval_data_file dataset/valid.jsonl \
    --test_data_file dataset/test.jsonl \
    --num_train_epochs 2 \
    --block_size 400 \
    --train_batch_size 8 \
    --eval_batch_size 16 \
    --learning_rate 2e-5 \
    --max_grad_norm 1.0 \
    --seed 123456
```

Other environment:
```
OS: Ubuntu 18.04
Pytorch: 1.12.0+cu102
GPU: 4 * Nvidia Quadro RTX 6000
```

At the end of the training script, I observe the following messages:
```
***** Running evaluation *****
Num examples = 8000
Batch size = 16
eval_loss = 0.0481
eval_map = 0.8678
****************
Best map:0.8678
****************
```

Thanks.

**Comment by guoday** [comment]
Please use 2 GPU. The more GPU you use, the less size of negative samples is.

**Comment by XZ-X** [comment]
I change the number of GPU to 2, and the MAP becomes 86.68. It does not change significantly.

That said, I just found that the performance on "test data" (`dataset/test.jsonl`) is close to 90. Maybe the number in the paper is on the "test data", instead of the "eval data" (`dataset/valid.jsonl`)?

**Comment by guoday** [comment]
yes. test data.

**Comment by XZ-X** [comment]
Got it. Then I can reproduce the reported number. Thanks for your prompt help! 👍
