### ISSUE TITLE
怎么使用我们自己的数据集的code-nl pair对CodeBERT进行mlm

### ISSUE THREAD

**Issue by EileenWang1228** [microsoft/CodeBERT#176]
您好，我想使用我自己数据集，按照[CLS]nl[SEP]code[EOS]的形式输入进CodeBERT，最终得到[CLS]的embedding，但是得到的embedding的效果不好。应该需要先使用我们自己的数据集对CodeBERT进行MLM吧

**Comment by guoday** [comment]
CodeBERT的MLM并不能得到好的embedding，这个我们在UniXcoder已经测试过了。你可以使用UniXcoder获得embedding，在很多实验中验证UniXcoder所获得的embedding是比较有效果的。https://github.com/microsoft/CodeBERT/tree/master/UniXcoder#1-code-and-nl-embeddings

**Comment by EileenWang1228** [comment]
非常感谢您的回复，您给的例子是单独对code和nl得到embedding的情况。我想要得到code+nl的embedding，是要按照<s> code_tokens </s> docstring_tokens </s>的形式输入嘛

**Comment by guoday** [comment]
你可以拼接起来当作code输入，也可以code和nl单独输入得到embedding再拼起来。这个取决于你下游任务的结果

**Comment by EileenWang1228** [comment]
非常感谢您，但是下面的model.tokenize的model是“microsoft/unixcoder-base”对吧，按照您的样例，我的代码如下：
tokenizer = AutoTokenizer.from_pretrained("microsoft/unixcoder-base")
model = AutoModel.from_pretrained("microsoft/unixcoder-base")
func = "def f(a,b): if a>b: return a else return b"
tokens_ids = model.tokenize([func],max_length=512,mode="<encoder-only>")
source_ids = torch.tensor(tokens_ids).to(device)
tokens_embeddings,max_func_embedding = model(source_ids)
但是会报错AttributeError: 'RobertaModel' object has no attribute 'tokenize'
如果我换成tokens_ids = tokenizer([func],max_length=512,mode="<encoder-only>")，会报错TypeError: _batch_encode_plus() got an unexpected keyword argument 'mode'

**Comment by guoday** [comment]
https://github.com/microsoft/CodeBERT/tree/master/UniXcoder#2-quick-tour

**Comment by EileenWang1228** [comment]
非常感谢，我明白啦，感谢您。
