### ISSUE TITLE
About CodeBERT code2nl task

### ISSUE THREAD

**Issue by treeAndRiver** [microsoft/CodeBERT#18]
I have a doubt: 
the NL-Code Discriminator (essentially RoBERTa) in your paper is trained with bimodal data, but I found that when perform code2nl tasks in the code you gave, you directly use this NL-Code Discriminator as encoder, I don’t know why you can do this. Because in the code2nl task, the input is only code, which is unimodal data, not bimodal data. Can you help me answer my doubts? Thank you very much!

**Comment by guody5** [comment]
In the pre-training stage, we use NL-Code Pair to learn both NL and Code representation. Although we use bimodal data in the pre-training stage, you can obtain NL or Code representation by taking only unimodal data as the input on downstream tasks, which is similar as [XLM](https://arxiv.org/pdf/1901.07291.pdf).

**Comment by treeAndRiver** [comment]
thank you for your reply. 
The following picture describes the difference between the input and output of the pre-training phase and the fine-tuning phase. Is this correct?
![show_diff](https://user-images.githubusercontent.com/68835157/103172925-1c2bf500-4892-11eb-9de8-3d8de9b509e0.jpeg)

**Comment by guody5** [comment]
The input of pre-training phase is [<s>,nl,</s>,code,</s>]. But in fine-tune phase, the input can be [<s>,nl,</s>,code,</s>], [<s>, nl, </s>], and [<s>, code,</s>], which depends on your downstream tasks. The output is representation of each token in both pre-training and fine-tune phases.
