### ISSUE TITLE
Questions about CodeReviewer 

### ISSUE THREAD

**Issue by SubhajitC-Hexaware** [microsoft/CodeBERT#181]
I am trying to run CodeReviewer on kaggle as is, but facing problems with the configuring .sh scripts, is there any generalized way to pass those values to run it properly on kaggle ?

**Comment by Lizhmq** [comment]
A simple (but not grace) solution is to modify the code in `config.py` and write your own arg class.
For example, you can define your own args class and then import it in corresponding `finetune_xx.py`:
```python
class FakeArgs:
    def __init__(self):
        self.train_epochs = 10
```
If you are not intereseted in parallel computing, the "torch distributed" arguments can be removed. You should set "local_rank" and "global_rank" to 1 and then directly run "python finetune_xx.py"
