### ISSUE TITLE
Questions about extracting code snippet's embedding

### ISSUE THREAD

**Issue by universetraveller** [microsoft/CodeBERT#182]
Hi, I have tried UniXcoder and CodeBERT recently, and got an extraordinary result. Now I'm going to extract some java code snippets' embedding by UniXcoder as their features, and I have 3 questions about it:
1) As the paper of UniXcoder, comments are useful for model to capture semantics, but based on my expriments, while I did not remove the comments of these code snippets, the result of code prediction would be bad (<mask0> will be decoded to be some irrelevant code in comments). If I want to extract features for these snippets, should I remove their comments before generating embedding?
2) As other issues, the max_length must be less than 1024, and its default is 512; while using UniXcoder, I found that the size of embeddings are static 768. Now I want to extract embedding for a snippet(may be a java method), and I focus on a line in it, if the lines of this method is 100 or more; for representing the context information of the line, is it recommanded to limit the number of context's lines to be less than some numbers(i.e. 25 before and after this line) or it is better to reserve all the method snippet?
3) I'm going to extract embeddings of two snippets(one is the edited ver of another) to represent their semantic difference. Is it suitable to use UniXcoder to do this task? Or are there some excellent works I have not found yet to do this task?
Thanks.
Best regards!

**Comment by guoday** [comment]
1. In general, comments should be useful for embedding. The reasons that lead to bad results may be 1) The input is incorrect (You don't need to extract comments individually and just keep comments in code) 2) The maximum input length is too short. 3) The comments may be meaningless for your task.
2. If you want to represent a line, using its context is a good idea. Whether to limit the number of context's lines depends on your experiment results.
3. If you can fine-tune UniXcoder on this task, it's suitable to use UniXcoder. If not, I guess that embeddings of UniXcoder are hard to capture the semantic difference. You can refer to this [paper](Towards Learning (Dis)-Similarity of Source Code from Program Contras) that pre-train a model to represent edit.

**Comment by guoday** [comment]
One suggestion for question 2. If you use context before and after a line to extract its embedding of the line, it may be better to use mean pooling on this line instead of the whole input.

**Comment by universetraveller** [comment]
Thanks for your reply and suggestions!
