### ISSUE TITLE
fine-tuning GraphCodeBERT?

### ISSUE THREAD

**Issue by Chris33Edwards** [microsoft/CodeBERT#184]
Hi!
First, I want to commend you for your hard and important work.GraphCodeBERT is pretrained in 6 programming languages which does not include the C programming language.I wanna GraphCodeBERT requires to be familiar with the code pattern of the C language.So how can I through transfer learning to fine-tuning GraphCodeBERT?

**Comment by guoday** [comment]
When you use C programming language, you can regard it as java or c# programming languages and extract the dataflow.

**Comment by Chris33Edwards** [comment]
> 

However, if I still wanna use C programming language data to fine-tuning unixcoder and GraphCodeBERT,how can I achieve that?

**Comment by guoday** [comment]
I am confused. Do you mean pre-training? If you just need to use C programming language data to fine-tuning unixcoder and GraphCodeBERT, you can directly use your own data to fine-tune unixcoder and GraphCodeBERT. Although unixcoder and GraphCodeBERT are pre-trained on 6 programming languages, they also can support other languages.

**Comment by Harshinibs10** [comment]
hi guoday  .  how can i train codebert model by SARD dataset  .
