### ISSUE TITLE
How to use this Codereviewer on HuggingFace

### ISSUE THREAD

**Issue by mpociot** [microsoft/CodeBERT#194]
Hi!

I want to see how I can use the codereviewer pre-trained models on Hugging Face.
Do I still need to train the model somehow? 
If I try to paste the demo JSON into the Hugging Face inference API/UI it doesn't return any good results.

Am I missing something?

**Comment by mpociot** [comment]
@celbree thank you very much.

Could you please help me figure out how I can do this?

I cloned the repository and downloaded all of the dataset files.
I then successfully ran the `bash finetune-cls.sh` script, which generated a bunch of checkpoint files.

Now how would I go about running `finetune-msg.sh` as the next step?

The finetune script is looking for these files: `preds.txt` and `golds.txt` (https://github.com/microsoft/CodeBERT/blob/master/CodeReviewer/code/run_finetune_msg.py#L82) 

As the default bash script is only passing microsoft/codereviewer as the model, these files don't really exist. (https://github.com/microsoft/CodeBERT/blob/master/CodeReviewer/code/sh/finetune-msg.sh#L27)

I'm sorry if these things are meant to be obvious - I'm trying to get started with AI / CodeReviewer and I just tried following the steps in the README. Any help is highly appreciated.

**Comment by rajanpanchal** [comment]
@mpociot.  Were you able to solve this?

**Comment by varaprasadtarunkumar** [comment]
hi,how can i finetune the model on my dataset ?
