### ISSUE TITLE
How does UniXcoder (code completion) train

### ISSUE THREAD

**Issue by timvandam** [microsoft/CodeBERT#197]
I am having trouble understanding how UniXcoder's training pass for code completion works. I would assume that it runs the model on the input sequences without that last token, and uses the last token as label/ground truth. Is this indeed how it works?
The code, for reference:
https://github.com/microsoft/CodeBERT/blob/master/UniXcoder/downstream-tasks/code-completion/model.py#L51-L65

**Comment by guoday** [comment]
Assume that input sequence is [A,B,C,D], it runs the model on the input sequences without that last token (i.e. [A,B,C]). Then the label for each token is the shift label (i.e. [B,C,D]).

**Comment by timvandam** [comment]
> Assume that input sequence is [A,B,C,D], it runs the model on the input sequences without that last token (i.e. [A,B,C]). Then the label for each token is the shift label (i.e. [B,C,D]).

Thank you for the response. How does this work with the loss? Is only the loss for D used to update the model?

**Comment by guoday** [comment]
the loss for [B,C,D]

**Comment by timvandam** [comment]
> the loss for [B,C,D]

Alright, thank you for the help :+1:

**Comment by timvandam** [comment]
Following up on this, I don't understand why the loss for [B,C,D] is used instead of only the loss for D. If the model is tasked to predict the last token (with ground truth D) wouldn't it make more sense to compute the loss only on the output and D? Or am I misunderstanding something

**Comment by guoday** [comment]
Since we need to generate ABCD instead of only D in practice, we need to calculate the loss of P(B|A), P(C|A,B), P(D|A,B,C).
