### ISSUE TITLE
Clarification about DFG extraction

### ISSUE THREAD

**Issue by imamnurby** [microsoft/CodeBERT#199]
Dear authors, 

Thank you for your amazing work!
I have 2 questions regarding the result of DFG extraction:
1. The result of calling [extract dataflow function](https://github.com/microsoft/CodeBERT/blob/305bab27920d57ba37964ab05ee7b1acdbb24416/GraphCodeBERT/translation/run.py#LL110C5-L110C27) is a list of identifiers and a list tuple where each tuple consists of 5 elements. I would like to clarify what is element 1, 2, 3, and 4, 5 in the resulted tuple?
2. When instantiating InputFeatures object inside convert_examples_to_features function, could you elaborate what is [dfg_to_dfg](https://github.com/microsoft/CodeBERT/blob/305bab27920d57ba37964ab05ee7b1acdbb24416/GraphCodeBERT/translation/run.py#L213)  and [dfg_to_code](https://github.com/microsoft/CodeBERT/blob/305bab27920d57ba37964ab05ee7b1acdbb24416/GraphCodeBERT/translation/run.py#L214)?

Thank you!

**Comment by guoday** [comment]
Yes.
