### ISSUE TITLE
About Data Format 

### ISSUE THREAD

**Issue by hmdgit** [microsoft/CodeBERT#2]
Hi,

I have a data in this format (doctring,code).

I figured out that the data you have used is in the following format:

`BooleanValue<CODESPLIT>URL<CODESPLIT>returnType.methodName<CODESPLIT>docString<CODESPLIT>code
`

In order to use the code for code search, I have the following concerns:

1. How can I generate BooleanValue for my dataset? Is there any benefit in code search? 
2. Though, I can work to generate 'returnType.methodName'. But, Is there any use of it in code search?
3. Is there any use of URL in training and evaluating model?

Kindly let me know about it.

**Comment by fengzhangyin** [comment]
The data format contains multiple fields, but only docstring and code are useful. Other fields just retain some information.

If docstring and code are from the same example, BooleanValue is 1. There is a detailed introduction in Section 4.1 of the [paper](https://arxiv.org/pdf/2002.08155.pdf).
