### ISSUE TITLE
GraphCodeBERT: Differences between the attention masks used in Equation 6 and used in downstream tasks

### ISSUE THREAD

**Issue by daiquocnguyen** [microsoft/CodeBERT#200]
Hi,
Thank you very much for your great work. 
I read the GraphCodeBERT paper and saw Equation 6 that the values in the attention mask are either 0 or a negative infinity. However, the values in the attention mask used for downstream tasks is either 0 or 1. 
This confused me.

Would you mind telling me the differences between these two attention masks? 
Thanks.

**Comment by guoday** [comment]
For the implementation of hugginface model, 0 in the attention mask will be converted to negative infinity and 1 will be converted to 0.

**Comment by daiquocnguyen** [comment]
Thanks for your clarification.
