### ISSUE TITLE
Accuracy of the generated data flow

### ISSUE THREAD

**Issue by smith-co** [microsoft/CodeBERT#201]
If I understand correctly, I can use the `GraphCodeBERT/clonedetection/parser/DFG.py` library to extract DFG for Java code. 

Steps seems to be:
 
- use the custom tree-sitter package to parse a tree 
- then construct the final DFG based on the parsed tree.

I have a few questions:

1. Can they handle inter-procedural data-flow analysis?
2. How accurate are the generated data-flow graph?

Looking forward to your response.

**Comment by guoday** [comment]
1. Yes.
2. We don't test the accuracy.
