### ISSUE TITLE
Questions about the inputs for getting embeddings

### ISSUE THREAD

**Issue by rongqipan** [microsoft/CodeBERT#204]
Hi,

Thanks for your work.
I tried to use CodeBERT, GraphCodeBERT and UnixCoder to extract Java code embeddings. 
However, for inputs to the models, I only used the Java source code, something like [CLS][JavaCode][SEP].

1. Should I also add comments to the inputs?
2. For GraphCodeBERT and UnixCoder, should I also add dataflow and also the flattened AST as input? Since I care about the execution time of the approach, so would adding that information (Comments, Dataflow and AST) make the time for getting embeddings much longer?

I would appreciate your kind suggestions,

Thanks.

**Comment by guoday** [comment]
1. It's better to add comments
2. You don't need to add dataflow or the flattened AST as input.

**Comment by rongqipan** [comment]
> 

Thanks for your reply and kind suggestions : )
