### ISSUE TITLE
请问graphcodebert在解析别的语言时，my-languages.so文件应该怎么修改

### ISSUE THREAD

**Issue by lihuiuyun** [microsoft/CodeBERT#211]

**Comment by guoday** [comment]
目前只支持这几种语言，还有c#:
https://github.com/microsoft/CodeBERT/blob/305bab27920d57ba37964ab05ee7b1acdbb24416/GraphCodeBERT/codesearch/run.py#L48-L64

**Comment by guoday** [comment]
my-languages.so文件不用改
