### ISSUE TITLE
How does embeddings actually work in clone detection?

### ISSUE THREAD

**Issue by lazyhope** [microsoft/CodeBERT#212]
Hi, thank you for your excellent work!

After looking through some issues on this repo regarding clone detection embeddings, my current understanding is that for GraphCodeBERT, given input `[CLS]code1[SEP]code2`, the output embeddings of `[CLS]` will be the input of a linear classification model to determine whether `code1` and `code2` are clone or not.

If my understanding is correct, now that I have fine-tuned a custom GraphCodeBERT model, when I compute the cosine similarity of the output embeddings of code1 and code2 during inference (ignoring the embeddings of [CLS] and [SEP]), will this result in a worse performance compared to classifying the [CLS] embeddings?

Thanks!

**Comment by guoday** [comment]
Yes. When you use `[CLS]code1[SEP]code2`, two codes will attend each tokens in each Transformer layer, which make classification better than cosine similarity of the output embeddings。

**Comment by lazyhope** [comment]
> Yes. When you use `[CLS]code1[SEP]code2`, two codes will attend each tokens in each Transformer layer, which make classification better than cosine similarity of the output embeddings.

Thank you so much!
