### ISSUE TITLE
Some problems with test dataset in code search

### ISSUE THREAD

**Issue by Mr-Loevan** [microsoft/CodeBERT#225]
In test phase, I note that testing the original datasets such as "batch_0.txt" shows normal MRR. However, when I shuffle batch_0.txt and re-test on this dataset (Cached Deleted), MRR is extremely low. Is there any restriction on test dataset sequence?

If I want to extend dataset, can I just append data into original test datasets?

**Comment by guoday** [comment]
please refer to https://github.com/microsoft/CodeBERT/issues/215#issuecomment-1427997821
