### ISSUE TITLE
could I download a pre-train model myself?

### ISSUE THREAD

**Issue by for-just-we** [microsoft/CodeBERT#24]
The example shows that we can load pre-train model like
`RobertaModel.from_pretrained("microsoft/codebert-base")`

but could I download first and then load like
```
config_path = 'pretrain_model/bert_config.json'
checkpoint_path = 'pretrain_model/bert_model.ckpt'
bert_model = load_trained_model_from_checkpoint(config_path, checkpoint_path,
                                                    seq_len=None)
```

**Comment by guoday** [comment]
please download the model from [here](https://huggingface.co/microsoft/codebert-base/tree/main)

**Comment by for-just-we** [comment]
> 
> 
> please download the model from [here](https://huggingface.co/microsoft/codebert-base/tree/main)

thank you, right now I have another question.

Does the model distinguish PHP, Go, Python and Java? 
In other words does this single model include all the programming languages mentioned in the paper. 
Or each programming language has its own model

The problem I face is php code classfication. So I just need a php token model.

**Comment by guoday** [comment]
We don't distinguish different language. We use the single model to handle all the programming languages。

**Comment by for-just-we** [comment]
> 
> 
> We don't distinguish different language. We use the single model to handle all the programming languages。

ok, but if I use a new php dataset to train for a task and that dataset contains some new token that the current model don't have.
would there any influences?

**Comment by guoday** [comment]
Since we use a BPE vocabulary, any new tokens will be tokenized some subtoken which is in the vocabulary, such as "Max_value" will be tokenized into ["Max", "_", "value"]. So I think there are not any influences when you use a new dataset.

**Comment by for-just-we** [comment]
> tokens

got it, thank you
