### ISSUE TITLE
Recommend way to aggregate semantic code embeddings

### ISSUE THREAD

**Issue by lazyhope** [microsoft/CodeBERT#249]
What would be the recommend way to aggregate different semantic code embeddings from the same repository to represent the overall semantic of the repository? Currently I am averaging the UniXCoder embeddings and using cosine similarity score to evaluate the result, but I am not sure if it is the right way.

Thanks in advance!

**Comment by guoday** [comment]
If you lack supervised data to fine-tune UniXcoder, the averaging approach is appropriate.

**Comment by lazyhope** [comment]
> If you lack supervised data to fine-tune UniXcoder, the averaging approach is appropriate.

Thank you!
