### ISSUE TITLE
Pretraining Instructions

### ISSUE THREAD

**Issue by tungngthanh** [microsoft/CodeBERT#28]
Can you share the instruction on how to train the GraphCodeBert model from scratch? I would like to add more data from different programming languages like C++ and may use the parallel corpus (let's say from geeksforgeeks)

**Comment by guody5** [comment]
Sorry, we don't plan to release the code of pre-training.

**Comment by tungngthanh** [comment]
yeah, how about the code of pre-training for CodeBert?

**Comment by guody5** [comment]
We don't release the of pre-training  CodeBERT yet.
