### ISSUE TITLE
what if I convert the codebert to longer tokenize?

### ISSUE THREAD

**Issue by brness** [microsoft/CodeBERT#281]
In this :https://github.com/microsoft/CodeBERT/issues/278#issuecomment-1646589487, I know we can expand the length of longcoder to unlimit length,  but I can also expand the codebert maximum length by this function, could this be a good choice? Do I have to re-train the model from the beginning?

**Comment by guoday** [comment]
Yes. It's good choice. You don't need to re-pretrain the model. Please refer to this [issue](https://github.com/microsoft/CodeBERT/issues/276)

**Comment by brness** [comment]
Thanks for ur kindly help~~
