### ISSUE TITLE
Missing Appendix in CodeReview Paper

### ISSUE THREAD

**Issue by watreyoung** [microsoft/CodeBERT#304]
The paper in CodeReviewer mentions a dataset cleaning process described in an Appendix in Section 3.3:"we clean the pre-training and downstream datasets carefully following the steps described in Appendix (attached as supplementary material).".

However, I couldn't locate this appendix in both the ACM library's published version and the arXiv pre-print.

Could you please clarify the availability or location of the referenced Appendix in the CodeReviewer paper? Access to this material would greatly aid in understanding the dataset cleaning steps crucial to comprehending the CodeReviewer workflow.

Thank you for your assistance.

**Comment by celbree** [comment]
Appendix is in the version 1 of our paper in arxiv. Here is the link https://arxiv.org/abs/2203.09095v1

**Comment by watreyoung** [comment]
Get! 

Thank you!

**Comment by binwensun** [comment]
thx !!!
