### ISSUE TITLE
Shift in loss?

### ISSUE THREAD

**Issue by mralexisw** [microsoft/CodeBERT#32]
Hi! Why do we need to have a shift [here](https://github.com/microsoft/CodeBERT/blob/1008a9a9698e4ad909ebabeb4a1e5c2a282bc304/GraphCodeBERT/translation/model.py#L73)?

**Comment by guody5** [comment]
Because the loss of generation is P(y_n|y_0,...y_n-1), you need to use vector of the last token to predict the next token. Therefore, you need to shift the label.

**Comment by mralexisw** [comment]
Thanks, @guody5 . Could you also explain why there is `min(len(dfg),0)` instead of a max? 
 https://github.com/microsoft/CodeBERT/blob/1008a9a9698e4ad909ebabeb4a1e5c2a282bc304/GraphCodeBERT/translation/run.py#L191

**Comment by guody5** [comment]
The code should be ` code_tokens=code_tokens[:args.max_source_length-3]`. Please ignore this.

**Comment by mralexisw** [comment]
thanks for the quick reply. to clarify, if the code is too long, we only keep the code and ignore the dataflow, right?

**Comment by guody5** [comment]
Yes.
