### ISSUE TITLE
What happens if there are more than 512 tokens in the train and test dataset?

### ISSUE THREAD

**Issue by nashid** [microsoft/CodeBERT#35]
Do I have to truncate the number of tokens to 512 before feeding it into the neural network?

I understand the limit of the number of tokens.

However, my question will the finetuning step fail if I have more than 512 tokens on a few occasions?

**Comment by guody5** [comment]
Since max position embedding =512, you have to truncate the number of tokens to 512. Otherwise, you will get error.
