### ISSUE TITLE
What is the inference cost in codesearch downstream task ?

### ISSUE THREAD

**Issue by VonNeumann2050** [microsoft/CodeBERT#40]
Can you guys tell me what is the inference cost, (for example the time for one query to be executed, and on which GPU ).

An approximation would be fine, is it like closer to 1 min or 10 ?  thank you very much.

**Comment by guody5** [comment]
This is the log for CodeSearch on GrapCodeBERT using 2 V100, about 3min15s/10955 = 0.02s one query.
12/18/2020 03:39:13 - INFO - __main__ -   ***** Running evaluation *****
12/18/2020 03:39:13 - INFO - __main__ -     Num queries = 10955
12/18/2020 03:39:13 - INFO - __main__ -     Num codes = 40347
12/18/2020 03:39:13 - INFO - __main__ -     Batch size = 64
12/18/2020 03:42:28 - INFO - __main__ -   ***** Eval results *****
12/18/2020 03:42:28 - INFO - __main__ -     eval_mrr = 0.6911

**Comment by VonNeumann2050** [comment]
Thank you very much I guess it's the same for the non graph version

**Comment by guody5** [comment]
Since the implementation of CodeBERT (feeding <query,code> to model and doing classification) is different from GraphCodeBERT (using dot product of vectors of query and code), CodeBERT will be too slow. About 1s per query on 4 V100.

**Comment by guody5** [comment]
We also provide the implementation of Siamese Model for CodeBERT. Please refer to this [link](https://github.com/microsoft/CodeBERT/issues/21#issuecomment-787848857), which will be faster than 0.02s per query.

**Comment by VonNeumann2050** [comment]
Thank you very much for this complete answer.
