### ISSUE TITLE
a problem in GraphCodeBERT/clonedetection

### ISSUE THREAD

**Issue by yuningkang** [microsoft/CodeBERT#41]
sir,When I ran the clonedetection task of graphcodebert according to your instructions, I encountered such a problem.
![image](https://user-images.githubusercontent.com/35360840/116812923-dd7db280-ab83-11eb-831e-599e74c498e6.png)

 Please help me solve this problem
@guody5
@tangduyu 
@fengzhangyin 
@Dong Shin

**Comment by guody5** [comment]
Follow [this](https://github.com/microsoft/CodeBERT/tree/master/GraphCodeBERT/clonedetection#tree-sitter-optional) to rebuild treesitter.
