### ISSUE TITLE
Number of epochs parameter is not used in Code2NL 

### ISSUE THREAD

**Issue by Nathan-Nesbitt** [microsoft/CodeBERT#42]
The following is declared in the `run.py` script for Code2NL, 

```py
parser.add_argument("--num_train_epochs", default=3.0, type=float,
                        help="Total number of training epochs to perform.")
```

It is never used in the script.

**Comment by Nathan-Nesbitt** [comment]
I have a fix for this and can make a PR, but I am not certain if this repo is for reference only?

**Comment by guody5** [comment]
Thanks. In fact, number of epochs are not used in this repo for re-implementing results of papers. You can find the new repo in https://github.com/microsoft/CodeXGLUE/tree/main/Code-Text/code-to-text. It will support epochs. Thanks again.
