### ISSUE TITLE
about using the CodeBERT

### ISSUE THREAD

**Issue by YouHao0809** [microsoft/CodeBERT#45]
If I want to realize the code search task of CodeBERT, may I load the weights from Microsoft and skip preprocess and fine-tune? I'm just confused cause training seems to cost a lot of time...

**Comment by guody5** [comment]
A demo of a finetuned CodeBERT model for the task of Code Search can be found here: https://drive.google.com/file/d/1ZO-xVIzGcNE6Gz9DEg2z5mIbBv4Ft1cK/view.
