### ISSUE TITLE
Zero Division Error when n_gpu=0

### ISSUE THREAD

**Issue by aniyaz** [microsoft/CodeBERT#47]
When the run.py file is compiled it throws an error `Zero Division Error` and the program halts without completely running. I think the line #352 in run.py of clonedetection (under GraphCodeBERT) is the issue.

`logger.info("  Instantaneous batch size per GPU = %d", args.train_batch_size//args.n_gpu)`

Kindly look into it.

**Comment by guody5** [comment]
please change `args.train_batch_size//args.n_gpu` to `args.train_batch_size//max(args.n_gpu,1)`
