### ISSUE TITLE
How could i further pre-train CodeBert?

### ISSUE THREAD

**Issue by mosh98** [microsoft/CodeBERT#52]
Hi,

How do I go about/get started for further pre training Code Bert on my domain Specific code.

Is there something thing I should look out for?

Can I use the traditional pre training pipeline for codeBert?

Is pre training with MLM enough or should i also do Replaced Token Detection as well, as part of further-pre training?

Any links or suggested reading materials would be hugely appreciated. :D

**Comment by guoday** [comment]
1. You can refer to huggingface pre-training script.
2. Yes, you can use the traditional pre training pipeline for codeBert.
3. In fact, only MLM is enough.


https://github.com/huggingface/transformers/tree/master/examples/pytorch/language-modeling

**Comment by mosh98** [comment]
I see that gives me confidence, huge thanks! 
Have a nice day!
