### ISSUE TITLE
Any chance of publishing smaller models?

### ISSUE THREAD

**Issue by tlby** [microsoft/CodeBERT#54]
Thank you for this effort!

[This collection of scaled down model pretrainings](/google-research/bert/commit/8028c0459485299fa1ae6692b2300922a3fa2bad) greatly accelerates rapid experimentation using BERT.  It would be very helpful to have similar model size variants to work with here.  Any plans?

**Comment by guoday** [comment]
HuggingFace has provided a small model similar with CodeBERT (https://huggingface.co/huggingface/CodeBERTa-small-v1). You can use this model. If you want to need to use this model. You can directly change "microsoft/codebert-base" to "huggingface/CodeBERTa-small-v1".

**Comment by tlby** [comment]
That's great, thanks so much!
