### ISSUE TITLE
Hard-coded language to extract data flow graph for Code Translation use case

### ISSUE THREAD

**Issue by MayankAgarwal** [microsoft/CodeBERT#55]
Hi, first of all, thank you for providing the code for your experiments. It made it very easy for me to reuse and experiment with it.

I'm trying to fine-tune the GraphCodeBert model for the code-to-code translation use case. While going through the `run.py` script, I realized that while parsers are initialized for individual languages, during tokenization the language is hard-coded to Java, and only its parser is used 
 https://github.com/microsoft/CodeBERT/blob/2e2e231a6e0ebf83a31c91db8fd2d60ae3b49a78/GraphCodeBERT/translation/run.py#L182

Shouldn't this be the language of the source code examples, or am I missing something?

**Comment by guoday** [comment]
Yes, you are right. Since I give an example whose input is java, I write hard-coded language here. When you run C#, you need to change to c_sharp. I will modify it, thanks.
