### ISSUE TITLE
Queries regarding GraphCodeBert

### ISSUE THREAD

**Issue by saichandrapandraju** [microsoft/CodeBERT#57]
Hi,

I tried GraphCodeBERT for translation and it was really nice!
I have a few queries though - 

1. What are the maximum source and target lengths that are supported ?
2. Seems the translation data focused on 'functions'. Can this be used for all kinds of programs which involve classes, test-cases, etc..?
3. Does the answers for above questions valid for CodeBERT as well?

**Comment by guoday** [comment]
1. Both are 512
2. Sure, you can use other kind of program. 
3. Yes. CodeBERT is same as GraphCodeBERT.

**Comment by saichandrapandraju** [comment]
Thanks @guoday .
