### ISSUE TITLE
OSError: Can't load config for 'microsoft/graphcodebert-base'

### ISSUE THREAD

**Issue by skye95git** [microsoft/CodeBERT#59]
I try to fine-tuned the graphcodebert to do code search, run
`lang=java
mkdir -p ./saved_models/$lang
python run.py \
    --output_dir=./saved_models/$lang \
    --config_name=microsoft/graphcodebert-base \
    --model_name_or_path=microsoft/graphcodebert-base \
    --tokenizer_name=microsoft/graphcodebert-base \
    --lang=$lang \
    --do_train \
    --train_data_file=dataset/$lang/train.jsonl \
    --eval_data_file=dataset/$lang/valid.jsonl \
    --test_data_file=dataset/$lang/test.jsonl \
    --codebase_file=dataset/$lang/codebase.jsonl \
    --num_train_epochs 10 \
    --code_length 256 \
    --data_flow_length 64 \
    --nl_length 128 \
    --train_batch_size 32 \
    --eval_batch_size 64 \
    --learning_rate 2e-5 \
    --seed 123456 2>&1| tee saved_models/$lang/train.log
`

There is an error:
OSError: Can't load config for 'microsoft/graphcodebert-base'. Make sure that:

- 'microsoft/graphcodebert-base' is a correct model identifier listed on 'https://huggingface.co/models'

- or 'microsoft/graphcodebert-base' is the correct path to a directory containing a config.json file

Is the download unsuccessful due to network reasons? Should I manually download and place the model in the folder `microsoft/graphcodebert-base`?

**Comment by guoday** [comment]
"microsoft/graphcodebert-base" should be downloaded automatically. If not, you can manually download in [here](https://huggingface.co/microsoft/graphcodebert-base/tree/main) by yourself.
