### ISSUE TITLE
Finetuned models

### ISSUE THREAD

**Issue by lambdaofgod** [microsoft/CodeBERT#6]
Do you plan to release models after finetuning?
If yes, could you provide download link?

If you're unwilling to share, could you at least specify how long does it take to train on machine with 4 P40 GPUs?

**Comment by guody5** [comment]
> Do you plan to release models after finetuning?
> If yes, could you provide download link?
> 
> If you're unwilling to share, could you at least specify how long does it take to train on machine with 4 P40 GPUs?

Sorry, we don't plan to release fine-tuned models. The number is reported by following this repo. It takes about 12 hours for ruby and javascript and 24 hours for other languages.
