### ISSUE TITLE
Ho wot get output string in Codesearch

### ISSUE THREAD

**Issue by Moshiii** [microsoft/CodeBERT#60]
Hi,

I am an researched on code retrieval and I want to reproduce your work for research purpose.

I fine-tuned your codesearch model and I run the run_classifier.py to get the test result.

But All I can see are two numbers, where is the generated code? How can I get the code sequence instead of two numbers?
![image](https://user-images.githubusercontent.com/7553188/126883389-9cf2f95a-db5c-4476-a4dc-50df40797b8c.png)
![image](https://user-images.githubusercontent.com/7553188/126883400-fa0d298c-a301-47cc-9371-b9a18c2642cc.png)

Thanks!

**Comment by guoday** [comment]
Please refer https://github.com/microsoft/CodeBERT/blob/master/GraphCodeBERT/codesearch/README.md#model-and-demo

**Comment by Moshiii** [comment]
Thanks for the Clarification and Demo link!. It can be a good idea to add a little explanation on the read me file so that other people will not asking this question any more.
