### ISSUE TITLE
how to use the Demo.py as codesearch tool?

### ISSUE THREAD

**Issue by Moshiii** [microsoft/CodeBERT#61]
Hi,
I received a guide from @guody that shows me the demo.py of GraphCodeBert's Siames Codesearch model.
However, This demo.py is not a real pipeline but rather again a evaluation of cosine similarity between the query and code:
![image](https://user-images.githubusercontent.com/7553188/126909593-7c6ea160-08d0-4cb9-bed8-bf6cca483ec2.png)

How Can I use the pre-trained python model as a code generation tool? Meaning that given an query Input, the tool produce a list of candidate codes snippet as output.

Thanks
Regards,

**Comment by guoday** [comment]
We just provide a demo for you to show how to retrieve code from a small candidates. You need to encode a corpus and retrieve them by your self.

**Comment by guoday** [comment]
Another way is to produce the result from line 242-254 in run.py.
