### ISSUE TITLE
How to fine-tune CodeBert and GraphCodeBert in code search task on my own dataset?

### ISSUE THREAD

**Issue by skye95git** [microsoft/CodeBERT#65]
I have collected a lot of github source code, and extracted the functions from them as CodeSearchNet data form:

![图片1](https://user-images.githubusercontent.com/41561936/129851736-ef77197c-5610-4d4a-8af4-2da6063b7a9c.png)

The python dataset I collected is about 220G. Now I want to fine-tune CodeBert and GraphCodeBert in code search task on the dataset. I have a few question:

1. The dataset is so large that I'm worried about running out of memory while training the model. Do you have any good suggestions?
2. The dataset is too large and the time to train the model is too long. Can CodeBert and GraphCodeBert support multi-machine and multi-card training?
3. I run training tests on a small portion of my own dataset. The initial loss of training differs greatly from that of training on Codesearchnet.

When I fine-tune CodeBert on Codesearchnet:

![截图1](https://user-images.githubusercontent.com/41561936/129853181-e407efda-f8c9-47eb-ada2-46ea5132c0a1.png)

When I fine-tune CodeBert on my own dataset:

![截图2](https://user-images.githubusercontent.com/41561936/129853242-f52f750e-d768-4bb3-9d9e-b610784d8989.png)

What should I do?

**Comment by guoday** [comment]
1. Transforming data form to [hugging datasets](https://huggingface.co/docs/datasets/), which can support large datasets.
2. Both CodeBERT and GraphCodeBERT only support multi-card training. You can use this [script](https://github.com/microsoft/CodeBERT/tree/master/GraphCodeBERT/codesearch#model-and-demo).
3. Maybe the query of CodeSearch is easy to retrieve. Therefore, the loss is small.

**Comment by skye95git** [comment]
> 1. Transforming data form to [hugging datasets](https://huggingface.co/docs/datasets/), which can support large datasets.
> 2. Both CodeBERT and GraphCodeBERT only support multi-card training. You can use this [script](https://github.com/microsoft/CodeBERT/tree/master/GraphCodeBERT/codesearch#model-and-demo).
> 3. Maybe the query of CodeSearch is easy to retrieve. Therefore, the loss is small.

Thanks for your reply! For the third question, I used the extracted functions directly as training data without data cleaning. Could it be the cause of the data? Do you have any suggestions for fine-tune codebert on new dataset?

**Comment by guoday** [comment]
You can use the [script](https://github.com/microsoft/CodeBERT/tree/master/GraphCodeBERT/codesearch#model-and-demo) directly and replace the dataset by your own dataset. Maybe you need to clean data before fine-tuning.

**Comment by skye95git** [comment]
> You can use the [script](https://github.com/microsoft/CodeBERT/tree/master/GraphCodeBERT/codesearch#model-and-demo) directly and replace the dataset by your own dataset. Maybe you need to clean data before fine-tuning.

Thanks! I will try it.
