### ISSUE TITLE
Issue "UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte"

### ISSUE THREAD

**Issue by hmdgit** [microsoft/CodeBERT#7]
Hi,

I have run the following script to perform **_inference and evaluation,_** but I am getting an error as **"UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte".** 

```
python CodeBERT/codesearch/run_classifier.py \
--model_type roberta \
--model_name_or_path CodeBERT/pretrained_models \
--task_name codesearch \
--do_predict \
--output_dir CodeBERT/data/train_valid/java \
--data_dir CodeBERT/data/train_valid/java \
--max_seq_length 200 \
--per_gpu_train_batch_size 32 \
--per_gpu_eval_batch_size 32 \
--learning_rate 1e-5 \
--num_train_epochs 8 \
--test_file CodeBERT/data/train_valid/java/test.txt \
--pred_model_dir CodeBERT/models/java/checkpoint-best/pytorch_model.bin \
--test_result_dir results/result.txt
```

I have taken a small subset of provided files. You can access them as

[train.txt](https://github.com/microsoft/CodeBERT/files/5089102/train.txt)
[test.txt](https://github.com/microsoft/CodeBERT/files/5089109/test.txt)
[valid.txt](https://github.com/microsoft/CodeBERT/files/5089110/valid.txt)

I am using [transformer library 2.5](https://github.com/huggingface/transformers/tree/v2.5.0)....

FYI...Following script, I have used for fine-tuning, which is working fine:

```
python CodeBERT/codesearch/run_classifier.py \
  --model_type roberta \
  --task_name codesearch \
  --do_train \
  --do_eval \
  --eval_all_checkpoints \
  --train_file train.txt \
  --dev_file valid.txt \
  --max_seq_length 200 \
  --per_gpu_train_batch_size 32 \
  --per_gpu_eval_batch_size 32 \
  --learning_rate 1e-5 \
  --num_train_epochs 8 \
  --gradient_accumulation_steps 1 \
  --overwrite_output_dir \
  --data_dir CodeBERT/data/train_valid/java \
  --output_dir CodeBERT/models/java  \
  --model_name_or_path CodeBERT/pretrained_models
```

Kindly guide me how can I resolve the issue?

**Comment by hmdgit** [comment]
Its resolved, when I give path like "CodeBERT/models/java/pytorch_model.bin", even though I have files in "CodeBERT/models/java/checkpoint-best/pytorch_model.bin"

**Comment by varadhbhatnagar** [comment]
I am having the same issue. Can you elaborate how you solved it?

**Comment by fengzhangyin** [comment]
Sorry, there is an error in “Inference and Evaluation” script.
“--pred_model_dir” should be the directory containing the model files, not the model file path.
I have fixed the error. You can run the script again following README.
