### ISSUE TITLE
fill-mask pipeline modifies tokens outside the mask location

### ISSUE THREAD

**Issue by breandan** [microsoft/CodeBERT#70]
Sometimes, the fill-mask pipeline changes the contents outside the mask. I suspect this may be an issue with tokenization, but whitespace is frequently added or removed unexpectedly. On line 6 of the method below, whitespace in the original code snippet has been removed. In other cases, newlines or other (usually whitespace) characters are rendered incorrectly. I am using the [the probing example](https://github.com/microsoft/CodeBERT#probing) in the README:

```
   | prompt given to model                                                            | predicted comment                                                                |
   |----------------------------------------------------------------------------------|----------------------------------------------------------------------------------|
1  | /**                                                                              | /**                                                                              |
2  |  * <mask>                                                                        |  * **Private methods * **                                                        |
3  |  */                                                                              |  */                                                                              |
4  |                                                                                  |                                                                                  |
5  |     private void notifyDisconnected() {                                          |     private void notifyDisconnected() {                                          
6  |         if (~listener~ ~!= ~null) {                                              |         if (**listener!=** null) {                                               |
7  |             listener.notifyRelayTunnelDisconnected();                            |             listener.notifyRelayTunnelDisconnected();                            
8  |         }                                                                        |         }                                                                        |
9  |     }                                                                            |     }                                                                            |
```

Not sure if this is an issue with @huggingface[/tokenizers](https://github.com/huggingface/tokenizers) or with CodeBERT specifically, but I thought I would post it here. Do you have any suggestions what might be going wrong? Does CodeBERT/GraphCodeBERT support any other pipelines or provide a way to sample a single token without returning the entire code snippet? Thanks!

**Comment by guoday** [comment]
It‘s surprising that you can predict the whole sentence, i.e. `**Private methods * **`.  The [pipeline](https://github.com/microsoft/CodeBERT#probing) can only predict a token in theory. I don't know how you do it. We use the same vocabulary the tokenizer as RoBERTa. There, it should be an issue with @huggingface/tokenizers.

Do you want to generate comment of a code snippet? Maybe you can describe your task so that I can give you some suggestions.

**Comment by breandan** [comment]
Hi @guoday, thank you for your reply. We append `<mask>` and sample up to 20 tokens using greedy decoding based on the argmax of `score` as [shown here](https://github.com/breandan/cstk/blob/6113ea4690acd203f81284cacb05c47b6b3827ed/embedding_server.py#L77). Unfortunately, the `fill-mask` pipeline returns the entire sequence instead of just the masked token, and sometimes modifies other parts of the code snippet which are not masked. Here are some more (clean) examples: https://gist.github.com/breandan/013af1a8b1113956222a56cff280feca

**Comment by guoday** [comment]
This's the output of the pipeline.
```
[{'sequence': 'if (x is not None) and(x>1)', 'score': 0.7237005829811096, 'token': 8, 'token_str': ' and'}, {'sequence': 'if (x is not None) &(x>1)', 'score': 0.10633718222379684, 'token': 359, 'token_str': ' &'}, {'sequence': 'if (x is not None)and(x>1)', 'score': 0.021604202687740326, 'token': 463, 'token_str': 'and'}, {'sequence': 'if (x is not None) AND(x>1)', 'score': 0.021227436140179634, 'token': 4248, 'token_str': ' AND'}, {'sequence': 'if (x is not None) if(x>1)', 'score': 0.016991229727864265, 'token': 114, 'token_str': ' if'}]
```

You can access to the `token_str` to get masked token.

**Comment by breandan** [comment]
Got it! I missed this key from the [probing section](https://github.com/microsoft/CodeBERT#probing), maybe it can be updated. Thanks!
