### ISSUE TITLE
Construct DFG for C and C++ code using DFG_csharp() function

### ISSUE THREAD

**Issue by MichaelFu1998-create** [microsoft/CodeBERT#74]
Hi there,
Based on my understanding about the code, the way that GraphCodeBERT construct DFG is to first utilize custom tree-sitter package to parse a tree then construct the final DFG based on the parsed tree.
For some reasons, I need to generate DFG for C and C++ code, I've added the custom tree-sitter package into my pipeline, but what I am wondering is that could I use the [DFG_csharp()](https://github.com/microsoft/CodeBERT/blob/3a029eb61198b64f3c540b0950c6228952d5c360/GraphCodeBERT/clonedetection/parser/DFG.py#L356) method to extract DFG for C and C++ code, are they compatible?  
Thanks very much for your help :)

Kind Regards
Michael

**Comment by guoday** [comment]
We don't implement extract function for C/C++. But you can try to use C# extract function to extract DFG of C/C++ code (i.e. you can regard C/C++ codes as C# codes and use C# tree-sitter. You don't need to add C/C++ tree-sitter). They are compatible but may lose some edges. You can try it.

**Comment by MichaelFu1998-create** [comment]
Alright, thanks for your help :)

**Comment by imamnurby** [comment]
@MichaelFu1998-create Hi, I am wondering whether if you could share the performance on C/C++ when using DFG_csharp() to process the input code?

**Comment by MichaelFu1998-create** [comment]
Hi @imamnurby, the performance seems alright to me, so it would be worth giving it a try.
