### ISSUE TITLE
Is it possible to further pretrain GraphCodeBERT on unsupervised MLM task

### ISSUE THREAD

**Issue by MichaelFu1998-create** [microsoft/CodeBERT#75]
Hello,
I am wondering if it is possible to further pretrain GraphCodeBERT on unsupervised MLM task from the checkpoint of "microsoft/graphcodebert-base".
I am working on datasets containing only C/C++ code, therefore, I hope the further MLM would make model understand more about the structure of C/C++ code.
Thanks for your help

Kind Regards
Michael

**Comment by guoday** [comment]
Yes. You can further pre-train GraphCodeBERT from the checkpoint of "microsoft/graphcodebert-base" on C/C++ code using unsupervised MLM task.

**Comment by mosh98** [comment]
I see, thanks!
