### ISSUE TITLE
Hyper Parameter tuning?

### ISSUE THREAD

**Issue by mosh98** [microsoft/CodeBERT#78]
Hi,
regarding fine tuning on CodeBERT,

What parameters should i choose to experiment with?

Should i follow the usual hyper parameters suggested on the original BERT and RoBERTa paper?

Asking because the codeBERT paper doesn't specify learning rate ranges.

Warm regards.

**Comment by guoday** [comment]
You can follow the hyper parameters in this repo for fair comparison. CodeBERT usually use 2e-5 or 5e-5 to fintune.
