### ISSUE TITLE
Fine model for code translation

### ISSUE THREAD

**Issue by partha117** [microsoft/CodeBERT#80]
Is there any possibility to release the fine-tuned model on the code translation task?

**Comment by monperrus** [comment]
Hi, this is Martin from KTH. We'd love to experiment with the model for the code refinement task. If you release them, that would be super useful and much appreciated. Thanks!

**Comment by guoday** [comment]
> Hi, this is Martin from KTH. We'd love to experiment with the model for the code refinement task. If you release them, that would be super useful and much appreciated. Thanks!

Sorry, we don't keep the checkpoint of fine-tuned model. You can follow the readme to fine-tune the model.

**Comment by monperrus** [comment]
ok, thanks, it's harder but indeed doable this way!
