### ISSUE TITLE
 I download a pre-train model myself

### ISSUE THREAD

**Issue by konL** [microsoft/CodeBERT#83]
Hi!
I am working on a task of searching whether 2 code fragment is semantically similar( maybe similar with codeSearch task ) , I have done some simple attempts .
 I download first and transform https://huggingface.co/microsoft/codebert-base/tree/main "pytorch_model.bin " into ckpt form, then load with bert4keras as mentioned in #24
```
config_path = 'pretrain_model/bert_config.json'
checkpoint_path = 'pretrain_model/bert_model.ckpt'
bert_model =  build_transformer_model (config_path, checkpoint_path,
                                                    seq_len=None)
```  
But I found that the result is not better than the result of using the original bert model, which is very weired.
Am i configure it correct? If not, could you show me an example?

**Comment by guoday** [comment]
You need to fin-tune the model first: https://github.com/microsoft/CodeBERT/tree/master/GraphCodeBERT/codesearch#model-and-demo

**Comment by konL** [comment]
> You need to fin-tune the model first: https://github.com/microsoft/CodeBERT/tree/master/GraphCodeBERT/codesearch#model-and-demo

Thank you for your replying! 
I have run the command in xxx
some errors occurred:
`run.py: error: unrecognized arguments: --lang=java --data_flow_length 64`
so I delete these2 lines. But I found that it stuck like below, could you let me know how to solve it? Thank you!
####################################
......- INFO - __main__ -   device: cuda, n_gpu: 1
####################################

**Comment by guoday** [comment]
Please follow readme in model-and-demo.

**Comment by konL** [comment]
Hi！Sorry for bothering again!
I have completed fine-tune the model
![image](https://user-images.githubusercontent.com/24618393/142368893-5658fcb2-2156-45b4-b1f5-04e8cd9f53c2.png)
Then again I load with bert4keras as mentioned in #24 (I transform model.bin into xx.ckpt first)
```
config_path = 'pretrain_model/bert_config.json'
checkpoint_path = 'pretrain_model/bert_model.ckpt'
bert_model =  build_transformer_model (config_path, checkpoint_path,
                                                    seq_len=None)
```
then I load bert and concatenate it with other layers like
```
bert = build_transformer_model(config_path=config_path,checkpoint_path=checkpoint_path, ......)
cls=....(bert.model.output)
dense=keras.layers.Dense(...)(cls)
...
```
I intend to train this model on my dataset, but the result is still not better than the result of using the original bert model.
(1) Am I configuring codeBERT correctly in this way?
(2) Or is it some reason for explaining my results?

**Comment by guoday** [comment]
Sorry. Since I never use keras, I am not sure what goes wrong. Maybe you need to check whether the transformation from pytorch model to keras model is correct.
