### ISSUE TITLE
Hi sorry to bother, i wonder why there's no script to refine GraphCodeBERT for code2nl task ? 

### ISSUE THREAD

**Issue by Anothernewcomer** [microsoft/CodeBERT#85]
Thanks for the reply !

**Comment by guoday** [comment]
Because we don't do the code2nl task in the paper. If you need, you can replace the dataset of refinement by code2nl datasets.

**Comment by Anothernewcomer** [comment]
And this may be a stupid question.. But it does bother me a lot : I realiaze the code2nl task use almost the same data as in the pretraining stage, I wonder whether it will make any difference to use a total new dataset to finetune ? or to use the same dataset is just as good.

**Comment by guoday** [comment]
Yes. The dataset of pre-training stage includes training datasets of code2nl task. If you use our released test dataset to evaluate code2nl task, using the same dataset is just as good because the distributions of training dataset and test dataset are same.
