### ISSUE TITLE
Using CodeBERT for code classification

### ISSUE THREAD

**Issue by dyussekeyev** [microsoft/CodeBERT#86]
Hi all.

Do CodeBERT suitable for code classification tasks?

For example, I have a lot of source codes of various categories (driver, game, email client, etc.). Is it possible to distinguish these types using CodeBERT?

Many thanks for considering my question.

**Comment by guoday** [comment]
[CodeBERT-classification-3.zip](https://github.com/microsoft/CodeBERT/files/7595309/CodeBERT-classification-3.zip)

I give an example for code classification. You can replace the dataset by your own dataset and change `config.num_labels=100` in run.py to the number of your categories.

**Comment by dyussekeyev** [comment]
Thank you very much!

**Comment by HosoyaKenn** [comment]
I used the classification code you provided, but I want to obtain a CSV file with vector representations of the training data after model training. Can you tell me how to modify the code to achieve this?
