### ISSUE TITLE
About the construction of DFG

### ISSUE THREAD

**Issue by wangdeze18** [microsoft/CodeBERT#88]
Thank you for your great work!  The code is very clear and concise to read.

I would like to ask about the logic behind each function in DFG.py. I would really like to implement CFG with reference, because I think there are times when CFG might be useful to understand the code as well.

**Comment by guoday** [comment]
We first keep a state table for all variables to indicate the last variable assignment position. And then we enumerate each variable  in AST to decide whether their values changes. If their value changes (e.g. "a" in a = b + 1), the state table will update the position of "a" and record the value flow of "a" (i.e. "a" comes from "b"+1). If their value don't change (e.g. "b" in a = b + 1), we just need to record  the value flow of "b" (i.e. "b" comes form the position of "b" in state table).

**Comment by wangdeze18** [comment]
Thanks for your reply! This seems to have errors in extreme cases, for example, unused statements that
```
a = b + 1
a = c * 2
```

**Comment by guoday** [comment]
For this statement, I don't find any problem according to my reply.

**Comment by wangdeze18** [comment]
Thanks for the quick reply. The first statement is overwritten by the second statement and is therefore invalid, so the two data-dependent edges introduced according to the first statement are also meaningless. Of course, this is a relatively rare case (but extracting the graph features as accurately as possible is of great importance for the subsequent processing).

**Comment by guoday** [comment]
Two data-dependent edges are introduced to the first statement is very important. This's also one of
 our motivation to leverage data flow. It can help to find dead code. As shown in Figure 1 of the paper, from the data flow, we can easily know that `x=0` is a dead code and can help model ignore the statement.

**Comment by wangdeze18** [comment]
From Figure 2, variable-alignment (dfg-to-code) considers x = 0. And, for data flow edge prediction (dfg-to-dfg), edge 7 and edge 9 will also consider the association with edge 3 (x = 0). Is it a better choice if edge 3 (x = 0) is not considered directly?

**Comment by guoday** [comment]
No, I don't think so. Considering `x=0` in data flow can help model know that `x=0` doesn‘t contribute `return x` since there's no path between `x^3` and `x^11` in the data flow. Therefore, the model may learn to ignore dead codes in downstream tasks and will be more robust.

**Comment by wangdeze18** [comment]
I think perhaps this could be artificially screened out during the preprocessing phase to focus on the more important program statements. Additionally, are there any guidance suggestions for CFG construction？

**Comment by guoday** [comment]
"I think perhaps this could be artificially screened out during the preprocessing phase to focus on the more important program statements. " 

Yes. You are indeed right and I total agree. However, filtering these meaningless codes does not seem easy in the preprocessing phase. Therefore, we hope model can learn this feature in the pre-training phase. Thank you for this great idea.

"Additionally, are there any guidance suggestions for CFG construction？"

Actually I am a NLP researcher and I don't know much about CFG. Therefore, I don't know if there are any tools that can do this.

**Comment by wangdeze18** [comment]
Thank you for your time！
