### ISSUE TITLE
use codebert in code clone detection

### ISSUE THREAD

**Issue by SimAST-GCN** [microsoft/CodeBERT#89]
Hi，i am trying to use codebert in code clone detection.  I notice that there is a codedetction implementation in graphcodebert/codedetection. 

Can i just change to 'config_name', 'model_name_or_path' and 'tokenizer_name' to 'codebert-base' to complete this task?

**Comment by guoday** [comment]
No. You can follow this [repo](https://github.com/microsoft/CodeXGLUE/tree/main/Code-Code).

**Comment by SimAST-GCN** [comment]
ok, thank you.

**Comment by iiceysong** [comment]
> Hi，i am trying to use codebert in code clone detection. I notice that there is a codedetction implementation in graphcodebert/codedetection.
> 
> Can i just change to 'config_name', 'model_name_or_path' and 'tokenizer_name' to 'codebert-base' to complete this task?

hello, how do you deal with this?
