### ISSUE TITLE
Use GraphCodeBERT to get C code embeddings

### ISSUE THREAD

**Issue by NKFelix** [microsoft/CodeBERT#92]
Can GraphCodeBERT be used to get embedding in the C language?
Is it possible to use the C language dataset for fine-tune to complete the downstream tasks of code cloning detection？
thanks

**Comment by guoday** [comment]
1. No. We don't support C language.
2. Please refer to this [repo](https://github.com/microsoft/CodeXGLUE/tree/main/Code-Code/Clone-detection-POJ-104). In order to use GraphCodeBERT, just need to change `microsoft/codebert-base` to `microsoft/graphcodebert-base` in all commands.
