### ISSUE TITLE
how to use GraphCodeBERT to get source code embeddings

### ISSUE THREAD

**Issue by tyhxyz** [microsoft/CodeBERT#94]
can you give a example just like  https://github.com/microsoft/CodeBERT#nl-pl-embeddings for graphcodeBERT
or how to get the CLS

**Comment by guoday** [comment]
1. If you don't want to use dataflow, you can directly change `microsoft/codebert-base` to `microsoft/graphcodebert-base` in  https://github.com/microsoft/CodeBERT#nl-pl-embeddings to get the code embedding.

2. If you want to use dataflow, it's not easy. You can follow this [Readme](https://github.com/microsoft/CodeBERT/tree/master/GraphCodeBERT/codesearch) and print `self.encoder(inputs_embeds=inputs_embeddings,attention_mask=attn_mask,position_ids=position_idx)[0][:,0]` in [here](https://github.com/microsoft/CodeBERT/blob/f01b02dfdae8e14f4a0ba61cbe92ba72060c7c76/GraphCodeBERT/codesearch/model.py#L19).

**Comment by tyhxyz** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by tyhxyz** [comment]
> 2\. [0][:,0]

thanks so much,

**Comment by tyhxyz** [comment]
> 1. If you don't want to use dataflow, you can directly change `microsoft/codebert-base` to `microsoft/graphcodebert-base` in  https://github.com/microsoft/CodeBERT#nl-pl-embeddings to get the code embedding.
> 2. If you want to use dataflow, it's not easy. You can follow this [Readme](https://github.com/microsoft/CodeBERT/tree/master/GraphCodeBERT/codesearch) and print `self.encoder(inputs_embeds=inputs_embeddings,attention_mask=attn_mask,position_ids=position_idx)[0][:,0]` in [here](https://github.com/microsoft/CodeBERT/blob/f01b02dfdae8e14f4a0ba61cbe92ba72060c7c76/GraphCodeBERT/codesearch/model.py#L19).

thanks so much

**Comment by Amal-AK** [comment]
> can you give a example just like https://github.com/microsoft/CodeBERT#nl-pl-embeddings for graphcodeBERT or how to get the CLS

I'm looking to do the same thing, have you figured out how to use graphcodebert-base to get embeddings using dataflow? , what are the inputs to this model ? and how to represent the dataflow graph as input to the model.

**Comment by guoday** [comment]
> > can you give a example just like https://github.com/microsoft/CodeBERT#nl-pl-embeddings for graphcodeBERT or how to get the CLS
> 
> I'm looking to do the same thing, have you figured out how to use graphcodebert-base to get embeddings using dataflow? , what are the inputs to this model ? and how to represent the dataflow graph as input to the model ?

You can follow this https://github.com/microsoft/CodeBERT/issues/31#issuecomment-801616113 to get graphcodebert embeddings.
