### ISSUE TITLE
How can I fune-tuning CodeBERT transformer?

### ISSUE THREAD

**Issue by majd-alhafi** [microsoft/CodeBERT#96]
Hello. 
This job is perfect, But I need a code to fine-tuning CodeBert on C programming language to do my downstream task.
Have a nice day.

**Comment by guoday** [comment]
You can find a similar task (classification, generation or retrieval) in this [repo](https://github.com/microsoft/CodeXGLUE/tree/main/Code-Code) and replace the dataset by your own.
