### ISSUE TITLE
About "microsoft/codebert-base-mlm"

### ISSUE THREAD

**Issue by yz-qiang** [microsoft/CodeBERT#99]
Hi,
codeBert is a nice job.
``microsoft/codebert-base`` was obtained based on the training method mentioned in the paper _CodeBERT:
A Pre-Trained Model for Programming and Natural Languages_, right? About ``microsoft/codebert-base-mlm``, how is it trained? Is fine-tuned based on ``microsoft/codebert-base``? Can you share with me the code that how to obtain(or fine-tuned the codeBert-base) this model? Thank you very much. :)

**Comment by guoday** [comment]
`microsoft/codebert-base-mlm` is a pre-trained model that only uses MLM objective.

**Comment by yz-qiang** [comment]
That is, ``Microsoft/Codebert-Base-MLM`` is not obtained based on fine-tuning of ``Microsoft/Codebert-Base``, right? Ok, I see. Thank you very much.
